### ISSUE TITLE
provide list of previous periods in a periodization/period collection in the data-entry page

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#1]
Via @atomrab: It would be helpful to have a list of the other periods in a given periodization/period collection on the page for the entry of a new period. This would help the user remember which periods from a large collection had already been entered, avoiding duplicates. It would also help to catch errors or typos in dates, since it would be more obvious that there was a gap or overlap between the existing period spans and the one being entered.

**Comment by ptgolden** [comment]
This was fixed a while ago. (though it's still not as pretty as it could be :angel:)
