### ISSUE TITLE
ORCID login putting up a 500 internal server error

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#104]
An attempt to log in to ORCID produces the following message in the pop-up:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

There's no other error message generated in the interface, so nothing else to copy. Up-to-date Chrome on a Windows 7 machine.

**Comment by rybesh** [comment]
Sorry about that; fixed now. Looks like this happened because we deployed a new version to fix some bugs, and the permissions for the database got screwed up so it was read-only. @ptgolden
