### ISSUE TITLE
Patch submission/ORCID authorization not working

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#105]
Logging in to ORCID produces "Signed in as" with no name message in both Chrome and Firefox (I checked my sign-in details on the ORCID website, and both email and password are correct). Patch submission process runs up to "Submit changes", but then clicking "Yes" causes interface to hang.

I cleared the cache in Chrome and the same thing happened. 

This is somewhat urgent, because I'd like to patch in the Library of Congress subject headings in time to contact the LoC to find out if they'd be willing to write for us for the next grant round.

**Comment by atomrab** [comment]
Sorry, if that wasn't clear, this is the message that appears on and after ORCID sign-in:

![image](https://cloud.githubusercontent.com/assets/4740995/11913432/39a751ee-a629-11e5-908c-65ea1ff9c96e.png)

**Comment by rybesh** [comment]
It looks like the response with credentials from ORCID after logging in has a blank (empty string) value for "name". Not sure if this is a temporary glitch or whether they've changed the API.

**Comment by rybesh** [comment]
Opened a separate bug in periodo-server for the ORCID API issue; leaving this open until we can confirm that the missing name is the only cause of the problem.

**Comment by rybesh** [comment]
Adam, can you try this again? ORCID seems to have fixed the problem on their side.

**Comment by atomrab** [comment]
It works. A little slow, but I ran through the whole process with the Library of Congress set and successfully merged it.
