### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#116]
I received this error after logging in with an ORCID and attempting to review patches on Firefox (v. 48.0.2).

Time: 9/7/2016, 9:58:42 AMVersion: 2.4.2Page: #/patches/=========UnknownError occurred when opening database _file_backends. The operation failed for reasons unrelated to the database itself and not covered by any other error code.

**Comment by atomrab** [comment]
I don't get the same error on Chrome, but I also can't see a patch that Elijah Fleming appears just to have submitted successfully.

**Comment by rybesh** [comment]
This looks like a problem with an expired HTTPS certificate; we're on it…
