### ISSUE TITLE
Norway is missing from the DBpedia list of countries

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#119]
It doesn't appear in any form that I've been able to figure out in the auto-populated list for spatialCoverage.

**Comment by atomrab** [comment]
Apparently so are Cambodia and South Korea (or "Korea" more generally) (per Eli F.).

**Comment by atomrab** [comment]
And Costa Rica (per Stefanie C.).

**Comment by rybesh** [comment]
Using Wikidata now, including Norway: https://github.com/periodo/periodo-places/blob/master/gazetteers/countries.json
