### ISSUE TITLE
Checkboxes for individual collections are not visible on the sync page for a local IDB

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#124]
The list appears with a "Select all" checkbox, but no checkboxes are visible for the collections in the list. 

![image](https://cloud.githubusercontent.com/assets/4740995/23564716/a64cecd6-0010-11e7-90ee-3bdecbfe75ae.png)

They actually seem to exist -- if you hover the cursor, it changes to a pointing finger, and if you click it once when it's in that state, a single collection will appear, just as if you had selected a checkbox. But it would be much more helpful to be able to see what boxes you are checking/have checked.

This is in Chrome Version 56.0.2924.87, Windows 8.

**Comment by rybesh** [comment]
You want to be able to check the checkboxes *and* see them? That seems like a lot to ask.

**Comment by atomrab** [comment]
That's just the way I roll. I have "High Maintenance" tattooed on my chest, man.

**Comment by rybesh** [comment]
@atomrab Are you still seeing this bug in Chrome on Windows 8? It is working in Chrome on Mac for me.

**Comment by atomrab** [comment]
Yeah, I'm still seeing it -- today's screenshot below. I don't want to purge the cache if I don't have to, because I have a ton of local information that I will then have to download and re-upload.

![image](https://cloud.githubusercontent.com/assets/4740995/26017135/bb283c24-372d-11e7-8ac8-8cb9bf744699.png)

**Comment by ptgolden** [comment]
This has been fixed in the rewrite of the change selection interface
