### ISSUE TITLE
Unable to create local IDB in Firefox 52.0.1, Windows 8

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#125]
Selecting IDB, entering a name, and clicking on Add produces the following error message:

Time: 3/3/2017, 12:56:47 PMVersion: 2.4.2Page: #p/=========UnknownError occurred when opening database test. The operation failed for reasons unrelated to the database itself and not covered by any other error code.

**Comment by rybesh** [comment]
Does this keep happening if you hard reload the page (`Ctrl-Shift-R`)?

**Comment by atomrab** [comment]
Yes.
