### ISSUE TITLE
Display all creators of given resource OR display first creator plus "et al."

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#132]
I know that it may be aesthetically problematic to display a long list of creators, especially for the current filter boxes, but for collections with multiple authors, the collection creators may prefer that the multiplicity is at least honored with "et al." in the display. I also think that on the main collection display page the large-font reference should include either the full list or an "et al." (I know you can see the full creator list right below, but we are trained to understand credit in terms of sole or multiple authors, and if the creators are provided in alphabetical order rather than authority order by the source, this may create a false impression of control on the part of the first creator in the list).

**Comment by rybesh** [comment]
We now show "et al" for lists of creators.
