### ISSUE TITLE
Patch merge not accepting deletions

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#134]
I created a local IDB to clean up the LoC collection, synced it with the existing LoC collection, and deleted a series of single-year "periods". I also removed several duplicates that had escaped editorial intervention in previous rounds, and created a single additional label for one entry. 

When I submitted the patch, the additional label was displayed as an edit, but none of the deletions were indicated. And when I merged the patch, none of the deletions were included. Only entire definitions were deleted, so I don't know whether this would also be true of the deletions of partial information. The IDB submitted as a patch is attached below.

[periodo-loc_fixing-1498119647152.txt](https://github.com/periodo/periodo-client/files/1094205/periodo-loc_fixing-1498119647152.txt)

**Comment by rybesh** [comment]
We actually ignore missing definitions and/or collections when generating patches, to avoid someone accidentally deleting data by generating a patch from just a subset of the data. But I can create and submit a patch from the command line to delete these. The patch is here if you want to merge it:
https://test.perio.do/#/patches/https://test.perio.do/patches/105/

(Note that the patch shows no changes, this is something we're working on fixing, but it is related to the fact that we don't typically allow DELETEs in patches)

**Comment by rybesh** [comment]
BTW please let me know when you merge patch 105.

**Comment by atomrab** [comment]
Merged.
