### ISSUE TITLE
Patch merge not recognizing collection information edits

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#135]
Stefanie accidentally submitted an early version of the Pyla-Koutsopetria collection that was missing an editorial note at the collection level, and I approved the merge. She then created a new IDB, synced the merged PKAP data, and added the missing editorial note. When she tried to submit this as a patch, the patch submission interface indicated "no changes detected". I have replicated the issue with the same file (attached below). Related to #134?

[periodo-Correction-1497468324279.txt](https://github.com/periodo/periodo-client/files/1094264/periodo-Correction-1497468324279.txt)

**Comment by rybesh** [comment]
This definitely seems to be a bug. @ptgolden any idea why no changes would be detected?

**Comment by rybesh** [comment]
I manually generated a patch for this; let me know when you merge it: https://test.perio.do/#/patches/https://test.perio.do/patches/106/

**Comment by atomrab** [comment]
Merged.

**Comment by ptgolden** [comment]
This should have been fixed. @rybesh and I will test to confirm

**Comment by rybesh** [comment]
Need to test to see if this happens in the new version.
