### ISSUE TITLE
Add ability to submit note with patch (to explain context or reasoning)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#138]
Not a problem while we're the only people patching, but it would help to explain the reasoning behind a particular edit on the part of an external editor, and it would also help to understand what's going on with unsolicited patches (who they're coming from, why, etc.). This will be a critical component if we're going to form a larger user community.

**Comment by rybesh** [comment]
+1 We should definitely have this.

**Comment by ptgolden** [comment]
We have the ability to comment as part of the patching process. Should we treat an initial "patch note" as a special part of a patch, rather than as an individual comment in a series of comments associated with a patch request?

**Comment by ptgolden** [comment]
Maybe as part of submitting a patch, a person would be prompted to add a note explaining what the patch is for. That note would then be immediately posted as an initial comment.

**Comment by rybesh** [comment]
> Maybe as part of submitting a patch, a person would be prompted to add a note explaining what the patch is for. That note would then be immediately posted as an initial comment.

I like this approach.

**Comment by ptgolden** [comment]
It would prevent having to touch the server much. If we added a field to a patch request, we would have to update the database schema, migrate the DB along with all its history, add attributes to resources, and maybe more? I wouldn't be opposed to that change, but it would take a lot more work..

For example, I don't think we have any way to import a history of patch requests into an empty database. Maybe we should add that? It would be useful for testing, at least.

**Comment by rybesh** [comment]
Now (in master) the patch submission process requires a comment to posted after the proposed changes are submitted.
