### ISSUE TITLE
Open ORCID popup a little higher on the screen

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#139]
This is a very, very minor issue, but the ORCID login popup always opens so low on my screen (in both Chrome and Firefox on PC) that I have to drag it up in order to log in. Is it easy to move that up by 100 pixels or so?

**Comment by rybesh** [comment]
@atomrab, are you seeing this with the new client?

 The window *should* open with a width of 500px, height of 600px, 500px from the top of the screen, and 500 px from the left of the screen. But if you've opened the window before and moved it someplace else, many browsers (inlcluding FF) will remember that and open it there.

**Comment by ptgolden** [comment]
I notice that the ORCID popup always opens so that the bottom is at the bottom of my screen. Is there any reason to have the top of the window be 500px from the top?

**Comment by rybesh** [comment]
🤷‍♂️

**Comment by ptgolden** [comment]
I should ask myself five years ago: 0ec2858dbdb588d6c9b7144340b1bcdbe3219756

I'm gonna take out all the position parameters

**Comment by ptgolden** [comment]
Done in b48d16546b6595c4fac48c0b14c4dc330ce91f00
