### ISSUE TITLE
502 Bad Gateway for ORCID auth

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#14]
Attempt to authorize PeriodO client to get ORCID produces 502 Bad Gateway error even when already logged in to ORCID system:

![image](https://cloud.githubusercontent.com/assets/4740995/6429964/823274e0-bfb9-11e4-806c-b389148da624.png)

![image](https://cloud.githubusercontent.com/assets/4740995/6429966/95d1cd02-bfb9-11e4-9ef1-cdf49a93f3f7.png)

**Comment by ptgolden** [comment]
Thanks, Adam. This is an issue with the server. Moved to periodo/periodo-server#25
