### ISSUE TITLE
Enhancement request (temporary): download files submitted as patches

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#140]
Until we have a formal review system and a client patch-review interface that allows one to examine patches at the level of individual definitions in new collections, I'd like to have the option to download the patch file as a json file that can be examined in the client. As unsolicited patches start to be submitted, this will give us a chance to check them before having to look up the submitter and write an email to him/her. If everything's in order, it will save us a step; and if there are problems, we can identify and explain them in the introductory email, rather than having to write first to ask the submitter to send a downloaded version.

**Comment by rybesh** [comment]
In the meantime, you can do this fairly easily with [curl](https://curl.haxx.se/download.html), if you have the number of the patch you're interested in, e.g.:
```sh
curl -L -H 'Accept: application/json' https://test.perio.do/patches/105/patch.jsonpatch
```

**Comment by atomrab** [comment]
If the current patch under review is 82 (that's how it appears in the URL), I get the message 

curl: (6) Could not resolve host: application 
This resource is not available as text/turtle

(I may or may not be running curl correctly, but I used the same script as above, substituting "82" for "105")

**Comment by rybesh** [comment]
I think on Windows you may have to enclose `Accept: application/json` in double quotes rather than single quotes:
```
curl -L -H "Accept: application/json" https://test.perio.do/patches/82/patch.jsonpatch
```

**Comment by rybesh** [comment]
Submitted patches are easily downloadable from the client now.
