### ISSUE TITLE
Formatting/best practices: start/end for dates expressed as single term?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#142]
In doing some housekeeping, I've come across several periods expressed in terms of a single date-range statement like "First half of the 5th century" (eg http://n2t.net/ark:/99152/p0sgtfrgw7t). In that case, the person doing data entry used the same expression for both the start and the end. Should we encourage that format, in keeping with our commitment to the original expression of the range? Or should we add some sort of clarification in the label to differentiate the start from the end? On a semantic level, saying "the Severe Period is the name given to the first half of the 5th century" expects your listener to understand that means the period begins at the beginning of the first half and ends at the end of the first half. This is how we're parsing it; do we need the label to reflect it too, or can we assume the user will get it?

**Comment by rybesh** [comment]
Here's what I think makes sense for these cases (taken from the current draft of the new guide):

> In some cases a source will describe the temporal coverage of a period using a single phrase, rather than separately describing the start and the stop. In a case like this, enter the description as the label for the start, but leave the label for the stop blank. Then turn off automatic date parsing, and fill in the standardized values for the start and the stop. For example a period described as covering the “last quarter of the twentieth century” would correspond to a range from starting in `1975` and stopping in `1999`, even though the textual description does not explicitly distinguish these two endpoints.

**Comment by atomrab** [comment]
I'm comfortable with this as a solution. Go ahead and close when you see fit.
