### ISSUE TITLE
Manually delete duplicate period definition in Danish collection

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#153]
I missed a reduplication when looking through the JSON expression of the patch that added the MUD collection. Per request of the contributor, please manually delete http://n2t.net/ark:/99152/p0r8d9ccwh4 (I'd delete it by patch, but that's still not possible).

**Comment by rybesh** [comment]
Fixed by https://github.com/periodo/periodo-validation/commit/68f238f4d78add54946a4ff83773017494f65604
