### ISSUE TITLE
Recognize Date qualifiers in the 2nd data entry page

### ISSUE THREAD

**Issue by sarahab** [periodo/periodo-client#18]
The first data entry page/step is "Add period collection" (5 fields). The issue occurs in the second data entry page/step, "Add period" (7 fields). Two of these fields, "Start" and "Stop", currently only accept a raw number for a year. We need to add capacity to recognize a date formatted like this example from the BM dataset: 749 (AH 132).  Also BC, BCE, etc.

**Comment by sarahab** [comment]
![20150309_add_period1](https://cloud.githubusercontent.com/assets/10801404/6559149/f5babaf8-c64e-11e4-8618-7ce05e704db9.jpg)
![20150309_add_period3](https://cloud.githubusercontent.com/assets/10801404/6559156/fc4f71b0-c64e-11e4-95fa-8d59af67ec8e.jpg)

**Comment by atomrab** [comment]
This is an issue that I think I identified earlier, but in an unhelpfully unclear manner. We need a separation between the LABEL field (the original label field in the spreadsheet) for a date, and an intermediate form in the format that Patrick's parser can handle. Or we need a mechanism to add new expressions, like a date expressed with a Hegira date attached to it.

**Comment by ptgolden** [comment]
Added option to disable automatic parsing in 03bf1b54502da3191c736f789bff7270fe993949.

It would be good to add additional calendars to the parser (including Hegira years), but that will have to wait until a later day.
