### ISSUE TITLE
Add all steps for publishing to npm to README and/or Makefile

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#187]
I'm not sure what steps you're following to publish to npm. is it:

1. make clean all
1. commit package-lock.json
1. tag with release version and push tag
1. make publish
1. increment version in package.json, commit and push

could we add all this (or whatever is correct) to the publish target in the Makefile?

**Comment by ptgolden** [comment]
Yes. But briefly:

```
make clean && make
git add package-lock.json && git commit
npm version (patch/prerelease/minor/major/etc)
make publish
```

I think the missing `npm version` (which wasn't obvious) was causing your problem. That command updates package.json, makes a commit, and adds a git tag.

https://docs.npmjs.com/cli/version
