### ISSUE TITLE
Locally editing canonical periods that refer to periods not available locally

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#189]
Currently if you import canonical periods into an in-browser database, but you do not import other canonical periods to which they refer (i.e. via broader or derived-from relations), browsing throws errors due to undefined related period values.

An easy way to test this is to import just the ARIADNE authority into an in-browser database, as most of its periods have derived-from links pointing outside the authority.

It's unclear to me how best to deal with this. Do we need to follow all links to related periods when syncing, and import them too?

**Comment by ptgolden** [comment]
Good question...

> Do we need to follow all links to related periods when syncing, and import them too?

The only other thing to do would be to say "Not present in dataset" when viewing a period with relations not imported.

Which approach do you think is better?

**Comment by rybesh** [comment]
I actually prefer the "Not present in dataset" I think as it makes it clearer what is going on … and maybe a warning when importing changes if there are periods being pulled in that refer to periods not being pulled in?

**Comment by rybesh** [comment]
This no longer throws exceptions, and I'm not sure we really need to mess with the importing changes workflow—I think it might be more confusing than it is worth. I've put some explanation in the guide that I think should suffice.
