### ISSUE TITLE
Exposing our URIs

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#19]
I don't know when we plan to make these part of our records (when we have a more permanent server home?), but it's going to be important quite soon to allow users to see and copy these (e.g. with the ARIADNE use case).

**Comment by ptgolden** [comment]
This is fixed (right @rybesh?), but the client needs to be updated to render periods for text/html requests (see #17)

**Comment by rybesh** [comment]
I think Adam means that the permanent URIs for periods and period collections need to be displayed in the client, and not just in the JSON-LD view. Adam, is that correct?

**Comment by ptgolden** [comment]
OK, that makes sense. I'll make sure the persistent links are visible.

**Comment by ptgolden** [comment]
However, as we discussed in the call on Tuesday, the permanent links can be considered permanent at this point.

**Comment by atomrab** [comment]
Yes, correct -- people who want to use our URIs in their random Filemaker database should be allowed to cut and paste from the user-oriented display, without having to go into the json (and then add the n2.net prefix too). A lot of the users I envision won't ever want to look at the json, and we should accommodate them, too.

**Comment by ptgolden** [comment]
Thanks. I will include a "copy this URI" to make that easier, too.

**Comment by ekansa** [comment]
Is this implemented yet, it does not seem so but maybe I'm missing something? I need an easy way to get stable URIs, as I'm starting to reference PeriodO now.

**Comment by ptgolden** [comment]
Implemented in d0a65ab094b15ecea8d15877bb2b718dc3def483

will be included when I put out version 1.0.0
