### ISSUE TITLE
maintain and display original start/stop and spatial coverage text

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#2]
via @atomrab: I wanted to move our discussions into the issue tracker, since I've found that as productive, if not more so, in other projects than long email threads. 

I don't know if one can add categories for labels for issues, but I'd like to have something to set apart actual bugs, enhancements, and questions from larger theoretical issues. Does anyone have a suggestion for a tag we can put in a title for bigger-picture issues like this one? Or is this just really an enhancement?

Now on to the issue.

I wanted to submit this issue to check in with you and Ryan about the display of the periods entered in the client you're building. One of the principles I assume we want to maintain is the preservation of the original terms in which a given period was described (so even if we're representing it as ISO dates, we keep the original statement that it was "early 5th century BCE-25 CE" etc.). Right now it looks like BCE, for example, gets translated to BC, and ISO-style dates (e.g. -700) aren't recognized by the parser. 

Obviously we'll need to normalize the dates on the back end and in the representation, but I'd find it helpful if the edit/browse interface retained the original label for display, either alone or in combination with the normalized ISO dates. I think it makes most sense to be explicit about any transformations that are happening between the temporal coordinates as expressed by the source and the information we're collecting.

Right now I think it's impossible not to mask the spatial transformations, though -- so when someone says that a period applies to "Mesopotamia", we're stuck making some deductions about the modern nations to which that applies. It will be interesting to see if we can get anywhere with ancient gazetteers or data sources -- Pleiades or maps of the extent of the Roman Empire, for example. But here too I'd be in favor of being as explicit about deductions as possible.

**Comment by sarahab** [comment]
Using the new client v.0.3.1, the data entry for an individual periodization currently lacks the following fields: alt-label, label_en, spatial_coverage_label, and notes_original. And source_locator, which seems particularly important. See these two screenshots: 
![20150330_collection_periodization](https://cloud.githubusercontent.com/assets/10801404/6898887/6a84091a-d6c2-11e4-8924-8ba7f42845fc.jpg) and 
![20150330_altlabel](https://cloud.githubusercontent.com/assets/10801404/6898896/7aea564c-d6c2-11e4-9822-0ddef53a7634.jpg)

This appears to be the case whether or not I'm signed in to my ORCID iD. I guess I'm not sure if leaving these fields out is intentional and why if so.

**Comment by rybesh** [comment]
Sounds like possibly Sarah is using a cached older version of the client?

**Comment by atomrab** [comment]
Should I have her empty the cache and reload? We're still using test.perio.do, right?

**Comment by atomrab** [comment]
Did the idb just go offline?

![image](https://cloud.githubusercontent.com/assets/4740995/6902426/686c1a16-d6d9-11e4-9890-2f2ea5bd5727.png)

**Comment by atomrab** [comment]
Sorry, it appears just to be Chrome, which I've broken somehow.

**Comment by atomrab** [comment]
Also, yes, it does look like Sarah's using a cached older version. If she clears the cache, will she lose all the entries she's added to her local copy?

**Comment by rybesh** [comment]
I'm pretty sure that a Ctrl-R or Command-R will refresh the JavaScript but
not clear the local storage, BUT let's wait to hear from Patrick before she
does that.

**Comment by sarahab** [comment]
Hi ... I was using the older version via this URL:
http://perio.do/periodo-client/# . Whether it was cached or not I am not
sure, but the presentation there is clearly the old version and I'll drop
that for future work. Now I'll use the new v0.3.1 to add period collections
& periods via this URL. https://test.perio.do/#p/periodo-client/ (that
backend; web doesn't seem to allow add/editing). Hopefully that sounds OK.
(All on Firefox browser).

**Comment by sarahab** [comment]
Working in https://test.perio.do/#p/periodo-client/ , I'm able to add a periodization within the Twist period collection. Then once it displays in my local backend, the Edit button disappears, till I switch to the JSON-LD view, switch back to List view, and the Edit button reappears. But it's nonfunctional. So it looks like one can only add new period collections while working in a local backend, which I'll do next.

**Comment by sarahab** [comment]
[Firefox] OK, I was able to add two periodizations in a NEW period collection, then the "Add period" button disappears after clicking it to add a third one. I'm still in the local backend but _can no longer add any more periodizations_. Refreshing brings me back to the local period collection list but then, still unable to add to it. (If it adds anything, clicking "Sign in" at the upper right is also nonfunctional). Please advise.

**Comment by ptgolden** [comment]
I see what's going on. Some changes I made broke that editing functionality. I will fix it this afternoon.

**Comment by ptgolden** [comment]
@sarahb, the problem of the add button is fixed.

The original start/stop text issue remains outstanding

**Comment by sarahab** [comment]
Hmm ... the "add period" button still has a bug: this time I was able to add 5 periodizations within a new collection before the "add period" button disappears. See screenshot:
![20150422_add_periodization](https://cloud.githubusercontent.com/assets/10801404/7288328/89f15e4a-e925-11e4-967a-6a9c60d42787.jpg)

After five (v0.6.5; using v0.3.1 before I got through two), the page completely freezes up, and all 3 Export options are nonfunctional too. View as JSON and View as RDF don't work, View Visualization blanks the screen / View List returns it back. Only thing that works is to "switch" the backend, choose the same local again, then I'm returned to the period collection page and can continue adding more periodizations to it...

**Comment by sarahab** [comment]
UPDATE: 5-periodization limit? When the "add period" button reappears, I click it and the page freezes again with no entry options for more periodizations. I wanted to get through adding 10-20 periodizations to this April22 patch, but it doesn't allow me to add more after five, so I'm going to submit a patch of five.

**Comment by ptgolden** [comment]
Hi Sarah,

Thanks. The five period limit must be significant. I'm not going to be able to work on anything until Friday afternoon, but I will tackle this then.

**Comment by ptgolden** [comment]
The start/stop display issue is now fixed.

I don't know what the five-period limit was all about, but there has been a complete overhaul since then. That problem does not exist anymore.
