### ISSUE TITLE
Sync with server

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#20]
Shouldn't the call to our server result in my browser downloading a local copy of all the data, which it would then display when I navigate to test.perio.do, until I perform a new sync? Currently it always begins with a blank screen, and I have to sync each time. If we're going to allow local/offline work, presumably the synced data need to persist locally until the next call.

**Comment by atomrab** [comment]
It also seems to be the case that sync with server is only downstream for *period collections* -- although the addition of a new period (e.g. Copper Age in Twist 2001) is persistent when one performs a server sync, the addition of a new collection (the British Museum) with a new period (the Abbasid dynasty) disappears when a new sync is performed. Presumably we want this to be upstream for both period collections and period definitions.

**Comment by atomrab** [comment]
Needless to say, this is sort of a problem for adding the British Museum period dataset.

**Comment by atomrab** [comment]
Deleting a period within an existing collection also seems to be passed on with a new server sync. So periods are operating normally, but new collections aren't being passed on.

**Comment by atomrab** [comment]
Ok, more complicated than I thought. In the browser (Chrome) in which I originally created the new period (now we're talking about Pre-Pottery Neolithic A in Life in Biblical Israel), when I perform a new sync and accept periods, that period is present in the dataset. But when I sync with the server in a different browser (Firefox) in which I haven't already been doing work, that new period doesn't show up. In both cases, I'm signed in with an ORCiD. Is this where the local dataset comes in? Have we not yet made it possible to upload new definitions to the main dataset?

**Comment by sarahab** [comment]
The new periodization added does seem to be propagating (even if it's uneditable--see #26 ). However this happened when I wasn't signed in to my ORCID iD. So it's not clear what the ORCID iD authentication does?

**Comment by rybesh** [comment]
What do you mean by "propagating"?

The ORCID authentication just gives us a way to identify you as a user. The
only time we need to identify you is when you submit a patch (i.e. propose
a set of changes to the PeriodO dataset). Currently you are only editing
your local dataset; when you're at a convenient stopping point, you will
submit a patch, which you and/or Adam can review, and then choose whether
to accept or reject.

If the patch is accepted, then changes will propagate to other clients
viewing the canonical PeriodO dataset.

Whether or not your patch is accepted, you can continue to maintain your
"forked" dataset locally, and share it with others however you like, either
by sending it via email or putting it on a web server (and the client can
load datasets from these places). It just won't be part of the official
Rabinowitz/Buchanan-curated dataset.

**Comment by atomrab** [comment]
In some cases, earlier attempts to make additions even to the local dataset weren't being reflected after navigation away from, and then back to a given collection. So work that was going in wasn't being saved, locally or otherwise. 

What will be the patch submission protocol? I assume it's not just hitting "sync with server". Do we have a way to view and accept changes at this point, or will it come later? Does a patch need to be accepted as a whole, or will there be a way to reject an individual erroneous period within a larger collection? That is, should Sarah try to submit pieces of the BM periodization at regular intervals, or wait and do the whole thing at once?

Also -- and this will be relevant to the two external users I'm asking to test right now -- what should one be sending by email to share a forked dataset? A serialized document in JSON-LD or Turtle?

**Comment by rybesh** [comment]
> additions even to the local dataset weren't being reflected after
navigation away from, and then back to a given collection

That is definitely a bug when it happens, so try to capture exactly the
steps that led to it occurring.

> What will be the patch submission protocol? I assume it's not just
hitting "sync with server". Do we have a way to view and accept changes at
this point, or will it come later?

Patrick is working on patch visualization. The idea is that there will be a
patch submission process of visualizing your changes, possibly selecting a
subset to include in the patch, and finally submitting the patch.

> Does a patch need to be accepted as a whole, or will there be a way to
reject an individual erroneous period within a larger collection?

It needs to be accepted as a whole, but patches can be of any size.

> That is, should Sarah try to submit pieces of the BM periodization at
regular intervals, or wait and do the whole thing at once?

That's up to you. We are aiming for a flexible workflow since its too early
to know what best practice is...

**Comment by sarahab** [comment]
[Firefox 36.0.4] So what I have now is a local backend called "April7 (idb)", which consists of a period collection with two periodizations. This was already asked, but now that I have an (incomplete) example, I'm wondering what the workflow is to submit it as a patch. For now, I'm only able to "Export" this as a CSV file (Excel, with a long multi-character filename) - the Text/Turtle and JSON-LD buttons are nonfunctional. Let me know what would happen next with this file. BTW, the Excel file it generates is similar to the spreadsheet I have the clean data in, but with four added columns (earliest & latest start & stop), though the one spatialCoverages column is blank for both periodizations despite what shows on the local backend (below, screenshot). 
![20150407_period_spatial3](https://cloud.githubusercontent.com/assets/10801404/7037731/bd842dce-dd6c-11e4-9a98-6d28b06d58e1.jpg)

Presumably one could just add more periodizations to their (Excel) submission file, though it's also important that the dates be normalized through the client.

**Comment by sarahab** [comment]
Here's a screenshot of what "Export" -> CSV generates (locally-named Excel file):
![20150407_period_spatial4](https://cloud.githubusercontent.com/assets/10801404/7037757/40fc5ec4-dd6d-11e4-9199-5c1e0712c3c2.jpg)

**Comment by ptgolden** [comment]
Hi Sarah, I've nearly completed the patch submission code. I should have it running tomorrow.

**Comment by sarahab** [comment]
Just FYI, it seems I'm only able to view the "Add backend" page features (to create a patch to then submit) after clearing my browser cache each time. https://test.perio.do/ initially shows up as literally a blank page, and when I click "PeriodO" at the top of it, it redirects to https://test.perio.do/#p/April7/ (my local backend name from a week ago) which is also, still a blank page. Was stuck, signed in & out of ORCID, ... till I cleared my browser cache (Firefox 37.0.2). Before and after screenshots below:
Before: 
![20150422_clearcache_b4](https://cloud.githubusercontent.com/assets/10801404/7287813/e88a3cb2-e91e-11e4-9bce-5ac933d12a9f.jpg)

After: 
![20150422_clearcache](https://cloud.githubusercontent.com/assets/10801404/7287815/eec8ec04-e91e-11e4-8754-90f2c8d1c277.jpg)

**Comment by ptgolden** [comment]
I'm marking this closed because patch submission and server sync has been rewritten, and the BM data will be in soon. New issues can go in new issues.
