### ISSUE TITLE
Javascript SyntaxError with Firefox

### ISSUE THREAD

**Issue by vindic** [periodo/periodo-client#201]
Seems that the site is no longer working with Firefox :

Error message in console Log : 

SyntaxError: invalid regexp group  // periodo-client-4.1.6.js:1:2

**Comment by rybesh** [comment]
Thank you! @ptgolden any chance you could take a look at this?

**Comment by ptgolden** [comment]
It was due to 0cff11799ef66ed859816ccd344e2dcfd09fa566. Firefox doesn't allow named capture groups in regexes

**Comment by ptgolden** [comment]
We should write a test for that function (ensureISOYear) before removing the naned groups

**Comment by ptgolden** [comment]
This is fixed in 4.1.7. I'll deploy after I teach today

**Comment by rybesh** [comment]
🙏
