### ISSUE TITLE
Navigate to authority page

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#204]
I'm finding the navigation from the period list to a given authority page non-intuitive. I realize that you can see what periods are in an authority with the filter function, and that you can see the information about the authority by clicking on a period and scrolling the page down, but the only way to get to an authority page itself is by clicking on the number next to a period in the browse list and then by clicking on the authority that shows up on that period's individual page. This is a pain if you want to download an authority, or check out additional information before using an authority as a filter term.

Is there a reason not to have a top nav option to get to a list of authorities on the browsing homepage for the Canonical dataset, as there is for the local? I found the collections tab in the old version very useful, and if one could sort by publication date or alphabetically by title or lead contributor here, it would be *very very* useful.

**Comment by atomrab** [comment]
As a side note, while I have internalized the fact that language and spatial coverage are filter tools, for some reason I keep expecting that clicking on the authority link will somehow take me to that authority. This wasn't the case in the old interface, despite the fact that it worked in exactly the same way. I think this may be because this entire column of values in the old interface had "Filters" as a header, while here the only reference to filters is "Filter by place", which leaves it unclear whether the other lists are also filters (especially if you can't figure out where else to get to an authority page).

**Comment by rybesh** [comment]
> I'm finding the navigation from the period list to a given authority page non-intuitive. I realize that you can see what periods are in an authority with the filter function, and that you can see the information about the authority by clicking on a period and scrolling the page down, but the only way to get to an authority page itself is by clicking on the number next to a period in the browse list and then by clicking on the authority that shows up on that period's individual page.

Agree that it is not intuitive, but you can get directly to an authority by clicking the link icon next to the **Authority** header when you have a period selected.

![link](https://user-images.githubusercontent.com/84592/69269775-bbff5580-0b9f-11ea-94c6-7db5eb8f20a9.png)

> Is there a reason not to have a top nav option to get to a list of authorities on the browsing homepage for the Canonical dataset, as there is for the local?

Patrick and I went back and forth on this. I was in favor of *not* having a separate authorities page, because I couldn't figure out what you could do from such a page that you can't do from the home browse page.

Would it help to have "view" links in the authority list filter?

> As a side note, while I have internalized the fact that language and spatial coverage are filter tools, for some reason I keep expecting that clicking on the authority link will somehow take me to that authority. 

We can try to group them more clearly and add a header.

**Comment by atomrab** [comment]
>Patrick and I went back and forth on this. I was in favor of not having a separate authorities page, because I couldn't figure out what you could do from such a page that you can't do from the home browse page.

Sorting by first author and publication year, if you know you want to find one, or a small number, of authorities that you want to work with. Without this option, you can scroll all the way through the filter list if you know the author/authority title, but you don't know when they were published; or you can sort the periods themselves by publication date, but then you have to scan those periods to find an authority you're interested in. Having a cleaner list of the authorities, from which you could jump right to that authority, was always useful for me when I was working on various things in the old client.

I totally hadn't noticed that little link icon. I suppose this will be simpler when the permalink sends you to the new client rather than the old one, so we can ignore this.

**Comment by rybesh** [comment]
We now (in master) have a browsable / searchable list of authorities.
