### ISSUE TITLE
Double click on period in browse list to get to period record page

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#205]
This is possible now only by clicking on the list item number next to the period, but it took me several tries to figure this out the first time I used it. Using a single click to "freeze" a period for display below the scrolling list made sense to me, but I expected that double-clicking anywhere in a given period row would take me to that period page. If this isn't a technical challenge, I think it would be more a obvious interaction for users.

**Comment by rybesh** [comment]
I agree, this would make sense.

**Comment by rybesh** [comment]
Added "view" link since double-clicking is not a common UI interaction in web pages.
