### ISSUE TITLE
Where should "Derived From" field pull values from? 

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#206]
User story: I want to make a new authority with periods based on another authority. Neither is in PeriodO yet.

Old workflow: I make the older authority first, submit the patch, and then make the authority derived from that one, with the PeriodO URIs minted for the older authority in the notes field.

New workflow: the Derived from field is a lookup that only searches the current local data source. If I put both the older and the newer authorities in the same data source, I will be able to express those derived-from relationships in a single data source that I can then patch -- but will the new URIs for the older authority then be inherited in the Derived-from relationship? If not, this is obviously a problem. If so, it makes things a LOT easier when you're dealing with two new sources, but more complicated when the older source is already in the Canonical dataset.

If the older authority is already in the Canonical dataset, I imagine that I'd have to import it into the local data source, rather than copy-pasting URIs. This is probably easier than the copy-paste way, but at the same time, it's inviting people to use more Canonical data locally, where they can mess around with it accidentally or deliberately, than the old way of making an authority, patching it, and then pasting URIs. 

This is not an issue for broader/narrower, since those relations have to be within a single authority.

**Comment by rybesh** [comment]
Here's how I put it in the new draft of the guide:

> Periods are often defined as modifications of periods defined by others. PeriodO records these relationships as **Derived from** links. Unlike broader and narower relations, derivation relations can (and usually should) relate periods from different authorities. To add derivation relations to periods from a different authority, that authority needs to be included in your editable data source.

So what you wrote here is exactly what should happen:

> New workflow: the Derived from field is a lookup that only searches the current local data source. If I put both the older and the newer authorities in the same data source, I will be able to express those derived-from relationships in a single data source that I can then patch

And yes, this shouldn't affect the existing authorities—unless you make changes to them, the patch won't include anything about them, except references from your new (derived) periods.

It should be clear now in the new reviewing interface if they've inadvertently made changes to existing periods, so I'm not too worried about that.

**Comment by atomrab** [comment]
Ok, that all makes sense. I like the idea that one can do both the original and derivative at the same time; we had a lot of trouble with getting the order right in the old system.
