### ISSUE TITLE
Allowing the use of the old client from the "Settings" page of the new client?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#207]
We've talked about leaving the old client view up for people who prefer the Classic version, though I imagine that we will have to turn off the edit functions. If we do continue to make this available, would it make sense to do it as an option under "Settings" in the new client? Or should we keep it up as a separate website altogether?

**Comment by rybesh** [comment]
I don't remember talking about that 😄 

I think this would be confusing, and I'd rather not maintain two code bases. Let's focus on making the new client work well for everyone.
