### ISSUE TITLE
Filter by time range

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#208]
We should try to reinstate this functionality, along with the old "hide outliers" option or something equivalent, to make it possible to filter quickly by time. I would also like to be able to filter by bounding box on the map, but you can already get partway there with the spatial coverage description list. There's nothing that allows the user to filter by time at the moment, and the timeline is essentially useless until you apply at least one filter because of those values I put in for the, er, beginning of the solar system.

**Comment by rybesh** [comment]
Yes for "select to filter" on both the timeline and the map. The latter may have to wait a bit: selecting a rectangle on the map should be straightforward (the Bits Coop code has support for it) but quickly searching a geospatial index of our gazetteer features to compare against the rectangle needs a fast in-browser geospatial database.

**Comment by rybesh** [comment]
Time slider filter now in master.
