### ISSUE TITLE
Navigation: returning to list of period collections from a particular collection

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#21]
Right now, when you select a particular period collection/source, you can't get back to the list of collections without hitting the browser back button, which takes you to a blank page where you have to sync again with the server.

**Comment by ptgolden** [comment]
This was a bit of a conceptual issue about how data was stored. It's made more explicit with the ability to load data from different sources (either web-based or local) added in 733efec95150c8a98d9fa56333bdd46a8f58b541

**Comment by sarahab** [comment]
This is just a language sorting-out comment: the client homepage currently presents the first action as "Add periodization", and within one of those, the next possible action as "Add period". Is it more accurate to call the first one a collection / source? I guess I just see different terms applied in different places (see screenshots).
![20150330_periodizations_to_collections](https://cloud.githubusercontent.com/assets/10801404/6899476/691771d0-d6c6-11e4-93c3-1b4d3bb56c0b.jpg)
![20150330_collection_periodization](https://cloud.githubusercontent.com/assets/10801404/6899482/71c4fe4c-d6c6-11e4-88e4-d96d6896b346.jpg)

**Comment by rybesh** [comment]
Yes, we should be using the term "period collection" instead of
"periodization" throughout.

**Comment by ptgolden** [comment]
This has been fixed for a while.
