### ISSUE TITLE
ORCID login is not working on Chrome (79.0.3945.88) or Firefox (71.0) on Mac OS (Sierra)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#211]
Clicking on the ORCID login link from "Settings" in the new client opens an empty pop-up window in both browsers.

Here's what I see when I click the link (I've been logged out of my ORCID, apparently, though I was using the client as myself a week ago):

![image](https://user-images.githubusercontent.com/4740995/72211762-4f655080-3496-11ea-8479-b743744c0b9c.png)

**Comment by atomrab** [comment]
Update: I was able to submit a patch in Chrome, where the client showed me as logged in via ORCID as myself. Maybe the login isn't working because the client already has me logged in? If that's the case, do I remain logged in until I either log out or clear the cache?

If the client does keep you logged in indefinitely, and as long as you're logged in shows a blank pop-up window if you click on the ORCID login link, it would be useful to have an indication somewhere in settings that a user is already logged in.

**Comment by rybesh** [comment]
Something is broken here. I am getting the blank window even with a fresh Chrome instance. Nothing is showing up in the error console … any ideas @ptgolden ?

**Comment by rybesh** [comment]
@atomrab, what version of Chrome are you on? I wonder if they've recently changed something that breaks the way we're doing this.

**Comment by rybesh** [comment]
Sorry, just saw that you already told us…

**Comment by rybesh** [comment]
OK, I think I found the issue. 58f7c5bac7ded9768e2d6bbd198f2a5f1a54f1c2 removed the `orcidURL` global and created a new `SignIn` component in `ORCID.js` that does not rely on it. However, the settings page is still using the old `SignIn` component in `Settings.js`.

I'll work on fixing this.

**Comment by rybesh** [comment]
We (meaning Patrick) have resolved the ORCID issue. Basically we had some old code that we forgot to remove. Because ORCID authentication is logically connected to a specific web data source (e.g. https://data.perio.do), the ORCID login should be in the "Data source" menu, not "Home". So that's where you should be logging in/out, and it is working — and we've removed the old non-working login under Home.
