### ISSUE TITLE
Question: protocol for sources in translation?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#212]
I am currently documenting the original chronological tables for a Classical Archaeology handbook written in German by Hoelscher in 2002. These are in turn the originals from which a series of periodizations in another Classical Archaeology handbook by Baebler, also in German, are derived, from which a periodization for Romanian Dobruja will be derived for ARIADNE+.

That's all straightforward. But I also have access to a later Italian edition of Hoelscher's book, which doesn't figure in this chain of derivation. From a data integrity standpoint, would it be better to:

a) Add Italian labels to the 2002 authority and make a note in the editorial notes for the source that these come from the later Italian edition; or

b) Add the Italian edition as a separate authority, in which case should the definitions be "derived from" the 2002 edition, even though they're actually in a "sameAs" relationship, with the only difference being the translation?

I think it's worth having a consistent answer to this question, since it's likely to come up in the future.

**Comment by rybesh** [comment]
I think a) makes more sense, since the 2002 edition essentially just added Italian labels rather than making an intellectual contribution (e.g. making changes to temporal extents).

**Comment by atomrab** [comment]
I'm comfortable with this. Feel free to close.
