### ISSUE TITLE
Inheriting coverage area from spatial coverage label

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#213]
In the old client, typing an existing "spatial coverage" label into that field during the entry of a period definition would automatically populate the "coverage area" with the list of countries provided for that label when it was first entered (so, for example, if there were a pre-existing "Aegean" with which one had associated the URIs for Greece and Turkey, selecting "Aegean" from a list of existing entries in the client would automatically add Greece and Turkey). 

This no longer seems to exist -- the label is entirely detached from the coverage area in the new client, so the second has to be filled in anew for each entry. I liked that feature a lot: not only did it save time, but it was a good way to avoid user error, especially in spatial labels parsed to include a lot of countries. Is there any way to bring that back in the new client?

**Comment by rybesh** [comment]
I didn't realize the old client did that. @ptgolden do you remember how this was implemented? Would it just search the current dataset for matching spatial coverage descriptions and use the spatial coverage entities associated with the first one found?

**Comment by rybesh** [comment]
The latest deployed version of the client now suggests places for spatial coverage based on the spatial coverage description: if there is a period **from the same authority** with "Aegean" as the spatial coverage description that is linked to Wikidata's Greece and Turkey, then entering "Aegean" as the spatial coverage description of a period **not yet linked to any places** will suggest adding Greece and Turkey to the spatial coverage links.
