### ISSUE TITLE
Cancel button on add/edit pages for periods and authorities

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#214]
The new client only offers a "Save" button on the add/edit pages. It may be the case that just using the back button to get out of a mistaken attempt to add or edit is fine, but I would prefer to have a "cancel" button that sent me back to the browse screen. Psychologically, I feel more confident that I didn't accidentally add something, and it makes it obvious that I have options other than "save". I assume there's no real risk that using the back button would accidentally add something, or that edits one navigates away from would still be propagated -- but users are familiar enough with sites that say "don't press the back button while we're processing" that a cancel button might just be reassuring.

**Comment by ptgolden** [comment]
Implemented in cd3197404834d76a29fa66c6b2eca40cc24ba4f9
