### ISSUE TITLE
Generation of URIs -- new workflow or bug?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#215]
I just submitted and then merged a new group of authorities with internal derived-from connections between them. In the past, the successful merging of a patch would instantly generate new ARK IDs for periods and collections. These three authorities, however (Hölscher 2002, Bäbler 2004, and Institute of Archaeology "Vasile Pârvan" 2020), submitted as a patch via the new client, still show "not yet assigned" and "not yet downloadable" for permalinks and downloads.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/4740995/72454862-51c1f600-3787-11ea-9ab5-6443e5063528.png">

Is this the result of a change in the workflow that entails a delay on the server side while the IDs and JSON representation are generated? Or has the patch review process changed? Or is this a bug that needs to be dealt with?

**Comment by rybesh** [comment]
This seems like a bug to me. It sounds like we are not refreshing the local dataset after the changes are merged, and we probably should be.

**Comment by rybesh** [comment]
This has been fixed. The three authorities that were affected by the bug have been assigned permanent URIs:

http://n2t.net/ark:/99152/p0wz8jk
http://n2t.net/ark:/99152/p093ht3
http://n2t.net/ark:/99152/p02kbfn

**Comment by rybesh** [comment]
For the record, the bug was not related to refreshing the local dataset but because skolem URIs were not being replaced with permanent URIs upon merge of the patch.
