### ISSUE TITLE
Periods should always get English labels

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#217]
When a period is saved, if the preferred label is in English, and there is no English alternate label, the preferred label should be copied to the alternate labels (this is how the old client worked).

If the preferred label is not in English, and there is no English alternate label, validation should fail.

**Comment by atomrab** [comment]
How does this interact with the workflow we discussed in #191? I agree with the point there that it's better for the source to submit the patch, but if validation fails without English alternate labels, the provider can't or won't add them, and we're not adding them ourselves and sending back a revised json file for them to load and submit, won't we be stuck?

**Comment by rybesh** [comment]
You're right—“validation should fail” is too strong. I was just thinking of some sort of indication that an expected value is missing, so that we can more easily catch it.

**Comment by rybesh** [comment]
Fixed in master.
