### ISSUE TITLE
Problem with viewing individual events in Canonical history

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#219]
I can see the list of events when I click on the History button for the Canonical datasource, but when I try to view a specific event, I see the following display:

![image](https://user-images.githubusercontent.com/4740995/73001653-6f670f00-3dc8-11ea-9371-da77d9b2a3fa.png)

**Comment by rybesh** [comment]
Looks like the history page is trying to load via ARK URI and so running to mixed content:
```
Mixed Content: The page at 'https://client.perio.do/?page=backend-patch&backendID=web-https%3A%2F%2Fdata.perio.do%2F&patchID=http%3A%2F%2Fn2t.net%2Fark%3A%2F99152%2Fp0h%23change-199' was loaded over HTTPS, but requested an insecure resource 'http://n2t.net/ark:/99152/p0patches/199/patch.jsonpatch'. This request has been blocked; the content must be served over HTTPS.
Web @ periodo-client-4.2.3.min.js:103

```

**Comment by rybesh** [comment]
In the meantime, you can see much of the same info for the canonical dataset under "Review submitted changes."

**Comment by rybesh** [comment]
Client version 4.4.1 fixes this and is deployed at https://client.perio.do
