### ISSUE TITLE
Disable "Submit changes" button while a patch submission is processing

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#229]
I think I've done this at least once myself (see patches I submitted on 2/14 at 9:24 and 9:25), and I also think I just observed it in the wild with a duplicate patch submitted a few seconds after the first (patches submitted by Izeta on 2/18 at 7:45): when there is a lag in the loading of a submission, the page shows no visible change, and it's easy to think you failed to click on the button. Since the button allows a new submission of the same patch, and since it's still functional while the server is processing the previous, this generates a duplicate, which is a pain for review.

Can we disable the button until the successful submission notification comes up? And is there any reason not to disable the submit button entirely on that page on after a single submission? I suppose you could select different parts of the same patch to submit at different times, but it seems like this will create more complications than it solves -- unless you have a specific use case in mind, or it's baked into the submission code.

**Comment by rybesh** [comment]
Yes, I've been meaning to file a bug about this myself.
