### ISSUE TITLE
Example of attempt to enter a period -- what's missing from interface currently

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#23]
Here's a concrete example. We're trying to add a period from Twist 2001, which exists as a collection in the server dataset. The period, diagrammed on page 17, is called "Copper (Chalcolithic Age)"; it lasts from 3200 BC to 2500 BC in "Europe", and is a sub-period of "the Metal Ages". 

Currently we can represent the label and the dates. We can construct Europe from all of its component countries, but it would be much more useful if we could point to a spatial gazetteer that will work with larger and smaller concepts -- currently we can't do "Europe" or "Sicily", only discrete nations. 

We also need to include information about language and script (lat, eng); original label (Copper); alternate label (Chalcolithic Age); English label (here probably Copper Age is best, inferring that's what the author meant by "Copper (Chalcolithic Age)") and source locator (page 17). This source also has a lot of broader/narrower relationships, which we probably want to capture at this point. 

How much of this can we push to the editorial notes field, to return to later, before we create a situation where we end up doing work twice by hand?

**Comment by ptgolden** [comment]
Which spatial gazetteer do you have in mind?

**Comment by ptgolden** [comment]
Sub-periods rely on periodo/periodo-data#15. You should enter these into the editorial notes for now.

Spatial coverage is partially remedied by f499073c42c0050cd332a557cf486126303a0583, which allows a user to choose a previously constituted spatial coverage description. This should be okay in the short term, however, there are some deeper issues here that we need to discuss.

Labels and alternate languages rely on periodo/periodo-data#16. I'd like to fix this today instead of punting to the editorial notes.

**Comment by atomrab** [comment]
"Derived from" in #15 is different from sub-periods (= "broader" in the spreadsheet). Derived from means a new period is a modification of an existing period (like, I'm using Shelmerdine's definition of LMIIIB, but I want to push the end-date down 50 years). A sub-period is like splitting Iron Age into Iron Age I, Iron Age II, etc. The first is genetic, the second hierarchical.

For spatial coverage, I'll take anything that can provide URIs and polygons for regional administrative divisions (e.g. "Sicily", "Toscana", "Texas") and for continental aggregations (e.g. "Europe", "North America", "Africa"). Geonames will at least resolve eastern, southern, northern Europe etc (e.g. http://www.geonames.org/7729883/northern-europe.html), and handles regions (e.g. http://www.geonames.org/2523119/sicilia.html). Does DBpedia do this too?

**Comment by ptgolden** [comment]
Let's discuss these in separate issues.

**Comment by ptgolden** [comment]
I moved spatial coverage to #26

**Comment by ptgolden** [comment]
Adam- I think I've addressed most of these things with my local development version. I'm just going to finish the label issues tomorrow and the newest version will be ready on Tuesday.

**Comment by ptgolden** [comment]
Editing labels fixed in 5c670394fb286496c8e820719634cb8932f2c919

**Comment by ptgolden** [comment]
All of these are possible to add in the editing interface except for derivedFrom information, which we can discuss in #16.
