### ISSUE TITLE
Give patches referenceable identifiers?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#230]
This is less important, but it would be easier to note issues related to specific patches if there were a better way to refer to patches than by the name of the submitter and the date and time. There are numbers, but they're consecutive and change each time a new patch is added, so they aren't useful for reference.

**Comment by rybesh** [comment]
Good point. They do have unique identifier, but we don't expose them in the client UI, and we should.

**Comment by rybesh** [comment]
We now (in master) show the sequential patch # on the patch review page and list of open patches.
