### ISSUE TITLE
Client is down -- error message

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#237]
I was in the middle of something, so if this is a scheduled outage, just let me know when it's likely to be resolved. Firefox 74.0 on Mac OS Sierra 10.12.6.

Client error
Error stack

OpenFailedError: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code.
create@https://client.perio.do/periodo-client-4.4.2.min.js:123:516076
_promise/p</p_<@https://client.perio.do/periodo-client-4.4.2.min.js:123:517038
executePromiseTask@https://client.perio.do/periodo-client-4.4.2.min.js:123:474072
Promise@https://client.perio.do/periodo-client-4.4.2.min.js:123:474616
_promise/p<@https://client.perio.do/periodo-client-4.4.2.min.js:123:516874
usePSD@https://client.perio.do/periodo-client-4.4.2.min.js:123:482246
newScope@https://client.perio.do/periodo-client-4.4.2.min.js:123:482099
_promise@https://client.perio.do/periodo-client-4.4.2.min.js:123:516835
tempTransaction@https://client.perio.do/periodo-client-4.4.2.min.js:123:488733
_idbstore@https://client.perio.do/periodo-client-4.4.2.min.js:123:506183
_read@https://client.perio.do/periodo-client-4.4.2.min.js:123:527765
each@https://client.perio.do/periodo-client-4.4.2.min.js:123:528671
each@https://client.perio.do/periodo-client-4.4.2.min.js:123:506978
exec/<@https://client.perio.do/periodo-client-4.4.2.min.js:1:24609
GetAllBackends@https://client.perio.do/periodo-client-4.4.2.min.js:1:15950
rawCase@https://client.perio.do/periodo-client-4.4.2.min.js:130:1293702
_curryN/<@https://client.perio.do/periodo-client-4.4.2.min.js:130:203761
[1744]</module.exports/<@https://client.perio.do/periodo-client-4.4.2.min.js:130:197890
Type/obj.prototype.case@https://client.perio.do/periodo-client-4.4.2.min.js:130:1294125
[3]</module.exports/</</<@https://client.perio.do/periodo-client-4.4.2.min.js:1:15859
loadData@https://client.perio.do/periodo-client-4.4.2.min.js:120:38006
[105]</</</resource.loadData@https://client.perio.do/periodo-client-4.4.2.min.js:120:49909
componentDidMount@https://client.perio.do/periodo-client-4.4.2.min.js:120:50771
Yj/<@https://client.perio.do/periodo-client-4.4.2.min.js:130:467923
[2067]</exports.unstable_runWithPriority@https://client.perio.do/periodo-client-4.4.2.min.js:130:835392
fg@https://client.perio.do/periodo-client-4.4.2.min.js:130:412619
Yj@https://client.perio.do/periodo-client-4.4.2.min.js:130:464329
Lj@https://client.perio.do/periodo-client-4.4.2.min.js:130:454739
ig/<@https://client.perio.do/periodo-client-4.4.2.min.js:130:412909
[2067]</exports.unstable_runWithPriority@https://client.perio.do/periodo-client-4.4.2.min.js:130:835392
fg@https://client.perio.do/periodo-client-4.4.2.min.js:130:412619
ig@https://client.perio.do/periodo-client-4.4.2.min.js:130:412857
jg@https://client.perio.do/periodo-client-4.4.2.min.js:130:412790
Rg@https://client.perio.do/periodo-client-4.4.2.min.js:130:451339
enqueueSetState@https://client.perio.do/periodo-client-4.4.2.min.js:130:417569
[2034]</E.prototype.setState@https://client.perio.do/periodo-client-4.4.2.min.js:130:585198
setApplicationRoute@https://client.perio.do/periodo-client-4.4.2.min.js:130:118861

Component stack

in Unknown
    in Unknown
    in div
    in Clean.div
    in UI:Box
    in Resource:open-backend
    in div
    in Clean.div
    in UI:Box
    in div
    in Clean.div
    in UI:Box
    in MenuedResource
    in div
    in Clean.div
    in UI:Box
    in div
    in Clean.div
    in UI:Grid
    in ThemeProvider
    in PeriodoApplication
    in Unknown
    in ThemeProvider
    in Provider
    in Unknown

**Comment by rybesh** [comment]
Seems like my server briefly dropped offline today, maybe right when you had a pending request? But I'm not seeing any issues now—are you still seeing this?

**Comment by atomrab** [comment]
Nope, this resolved itself. But now I see this when I attempt to submit the collections involved:

![image](https://user-images.githubusercontent.com/4740995/78075282-dcb79300-7369-11ea-927e-c82275afc95c.png)

**Comment by atomrab** [comment]
Oops, never mind. It wanted me to log out of ORCID and log back in, apparently, though I didn't get the "log back in message" this time.

**Comment by rybesh** [comment]
Possibly network issues again… my home internet is pretty unstable these days.
