### ISSUE TITLE
Add edit button for period collection

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#24]
If a mistake is made in the creation of a period collection, there's currently no way to go back and fix it or add to it. The attributes of a period collection need to have the same editorial control for authorized users as the period definitions within it.

**Comment by atomrab** [comment]
We also probably want to have a delete button for period collections, at least for admins, in case an entire collection turns out to have some fundamental problem.

**Comment by ptgolden** [comment]
Added in c8500e6b16628d2e93dd7d6e6c81d51b48669a87
