### ISSUE TITLE
Remove Lerna and refactor modules after npm 7 is released

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#244]
A while ago, we began using Lerna in order to avoid a lot of `require('../../../../backends/actions.js')` and similar deep nesting. We wanted to do that so that we could change APIs of different parts of the client without having to deal with fixing nested paths in every call to `require` to changed parts.

Right now, the module structure looks like:

```
modules/
    org-async-actions
    org-layouts
    periodo-app
        src/
            auth
            backends
            db
            forms
            graphs
            layouts
            linked-data
            main
            patches
    periodo-common
    periodo-date-parser
    periodo-ui
    periodo-utils
```

Another reason we started using Lerna was to publish some of these submodules independently so that they could be used in other contexts. These are: `org-async-actions`, `org-layouts`, `periodo-date-parser`, `periodo-utils`. Once I started using the first two in other projects, I moved them to their own repositories to avoid editing the periodo-client codebase and running through the Lerna publishing/versioning rigamarole every time I need to change an API. This is, I know, totally contrary to the idea of the "monorepo" that Lerna is meant for.

But really, the main reason we wanted to switch to Lerna was sound-- to be able to change different parts of the codebase without having to mess with requires all over the place. This is something that is easy in Python, for instance, but not with node/npm. The only builtin way to do it is using [symlinks in `node_modules`](https://github.com/browserify/browserify-handbook#avoiding-).

It looks like this will change with the release of npm 7 and its inclusion of [workspaces](https://github.com/npm/rfcs/blob/latest/accepted/0026-workspaces.md). I think that will be a good opportunity to get rid of a dependency (that I never really loved in the first place), and to rearrange how we organize the "submodules" of our project. I think, for the longterm ability to keep editing the client, it would make sense to rearrange the modules like:

```
modules/
    periodo-app
    periodo-auth
    periodo-backends
    periodo-db
    periodo-forms
    periodo-graphs
    periodo-layouts
    periodo-linked-data
    periodo-patches
    periodo-common
    periodo-date-parser
    periodo-ui
    periodo-utils
```

That is, removing the `org-*` packages from the periodo-client repository, moving `modules/periodo-app/src/*` into `modules/`, and renaming `modules/periodo-app/src/main` to `modules/periodo-app`.

It always struck as weird that we had a top-level module structure, and then a kind of module structure within `modules/periodo-app/src`. This would remedy that, and allow changing the different sub-parts of the client without dealing with that path situation.

(This is not urgent by any means-- just wanted to jot it down)

**Comment by rybesh** [comment]
I'm in favor of this. When we do it, we might also think a bit about the possibility of partitioning the JS bundles we create. In particular, I'm wondering if we could arrange things so that there is one smaller bundle with the libs needed for read-only browsing of PeriodO data, and one "complete" bundle for the small minority who will actually be creating local databases, editing periods, etc. For example, the former don't need `dexie` or `language-subtag-registry`.

But to make those decisions we need to understand what proportion of the minified bundle each lib takes up (see #249).

**Comment by ptgolden** [comment]
Unfortunately, the language tag registry is used in non-editing situations, to assign a label to a language tag:

https://github.com/periodo/periodo-client/blob/master/modules/periodo-ui/src/diffable/Value.js#L32-L38
https://github.com/periodo/periodo-client/blob/master/modules/periodo-app/src/layouts/authorities/Facets/index.js#L13-L17
https://github.com/periodo/periodo-client/blob/master/modules/periodo-app/src/layouts/authorities/Facets/worker.js#L8-L12

**Comment by rybesh** [comment]
Ah, forgot about that. Oh well, probably not the most important optimization we could make.

**Comment by ptgolden** [comment]
Moot point! We replaced lerna with using symlinks (f6b8a9fa90df496c046893afe67240dfca158ec8). We can revisit "de-nesting" periodo-app another time if we want to.
