### ISSUE TITLE
Source maps are broken?

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#249]
Trying to use [`source-map-explorer`](https://github.com/danvk/source-map-explorer#readme) to examine our browserify bundle results in errors:
```
$ source-map-explorer dist/periodo-client-4.4.3.js
dist/periodo-client-4.4.3.js
  Your source map refers to generated column 1 on line 22, but the source only contains 0 column(s) on that line.
  Check that you are using the correct source map.
```
Adding a `--no-border-checks` flag gets past that error, but the resulting visualization is useless:

<img width="546" alt="Screen Shot 2020-05-25 at 5 26 30 PM" src="https://user-images.githubusercontent.com/84592/82844037-ff1ee600-9eac-11ea-8a4b-bad1b0b3db7f.png">

**Comment by rybesh** [comment]
The reason I wanted to examine the bundle was to see if there are ways we might slim it down a bit from its current 3.6M minified size.

**Comment by ptgolden** [comment]
Not sure what's going on, but you can also try <https://github.com/hughsk/disc>

**Comment by rybesh** [comment]
I tried `disc`, and it runs OK on the browserify bundle, but not after minification (which might just be a matter of fiddling more with `terser` options). It shows the language subtag registry taking up a lot of space, but that also seems like the kind of thing that might minify pretty efficiently. 🤷‍♂️ Maybe not worth worrying about.
