### ISSUE TITLE
Bringing dependencies up to date

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#250]
I've now brought all our dependencies up to date except:
```
 clean-tag           ^1.1.0  →  ^3.1.1
 dexie               ^1.5.1  →  ^3.0.1
 natsort             ^1.0.6  →  ^2.0.2 
 styled-components  ^3.4.10  →  ^5.1.0
 styled-system       ^2.3.6  →  ^5.1.5
 system-components   ^2.2.3  →  ^3.0.3
```
[`clean-tag`](https://www.npmjs.com/package/clean-tag) is deprecated and presumably no longer needed after [upgrading `styled-components`](https://github.com/styled-components/styled-components/releases/tag/v5.1.0).

[`system-components`](https://www.npmjs.com/package/system-components) is also deprecated, and I'd prefer to *not* use `@rebass/components` because I don't trust jxnblk.

I tried out `dexie@3.0.1` and it seemed to work fine, but I'd rather have @ptgolden confirm that.

I tried `natsort@2.0.2` and got weird errors thrown from inside workers that I could not understand and Googling turned up nothing.

**Comment by rybesh** [comment]
@ptgolden If you haven't started on this, I'm happy to do the `styled-*`-related upgrades. Just let me know if you would rather do it yourself.

If you could look at the `natsort` issue, that would be great. And like I said I'd like your sign-off on the `dexie` upgrade since you know in more detail what API features we're relying on.

**Comment by ptgolden** [comment]
I have Dexie updated on my own branch so you can revert that one. I can look at natsort

**Comment by rybesh** [comment]
I didn't commit any changes to the `dexie` version. All the libs listed above are untouched

**Comment by ptgolden** [comment]
oh, duhhhh. Sorry. I have a big commit that's been holding me up that I'm putting up presently.

**Comment by ptgolden** [comment]
Did you mean to remove the inter-project dependencies in e55520f8293c424ce97fee561d83aa31ebcc2b4b? (e.g. `periodo-ui`, `periodo-common`) It causes the project not to build anymore from a fresh install. I'll fix it in my branch, just wanted to point it out

**Comment by rybesh** [comment]
I removed them because they make it impossible to run `npm install` within each subproject, e.g.
```
periodo-app $ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for periodo-utils@^5.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'periodo-app'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryanshaw/.npm/_logs/2020-06-02T18_48_38_086Z-debug.log
```

But if they're removed and we use `npm link` instead, then `npm install` works within subprojects and the lerna build works too. But, you're right, then the build from scratch will fail until you do `npm link`. That could be added to the Makefile but I guess that's kind of a pain.

Being able to install each subproject independently isn't critical but I occasionally find it useful for figuring out dependency issues. It's also kind of confusing to specify a specific version in package.json when what's really going on is that the code from the local copy of the subproject is being used (which is what `npm link` makes clearer IMO).

But I'm OK with leaving it as is since we're going to revisit this when npm 7 comes out anyway.

**Comment by ptgolden** [comment]
> But if they're removed and we use npm link instead, then npm install works within subprojects and the lerna build works too. But, you're right, then the build from scratch will fail until you do npm link. That could be added to the Makefile but I guess that's kind of a pain.

This is what we had been using Lerna to do. I have never run `npm link`, and it's not part of the makefile.

> It's also kind of confusing to specify a specific version in package.json when what's really going on is that the code from the local copy of the subproject is being used 

Yes, it is. But we aren't really changing versions of internal packages anyway. The version could just be `"*"`. It doesn't make logical sense, and it's annoying, and it sucks, but again... it's not so much to buy into the idea of "workspaces" that can be independently published; it's to avoid `const { Button } = require('../../../../ui')`. You're right though, I don't really want to manage the dependencies between the modules, I just want to use them among one another.

We could forget Lerna, forget npm workspaces, and [just symlink each thing into `node_modules`](https://github.com/browserify/browserify-handbook#symlink), with one root `package.json`. I'm in the middle of a lot of fiddling with deps, so now is not a good time, but I'll look into it after. It could just be as easy as

```
MODULES := $(wildcard modules/*)

SYMLINKED_NODE_MODULES := $(prefix node_modules,$(MODULES))

all: $(SYMLINKED_NODE_MODULES) ...

node_modules/%:
    ln -s $(replace node_modules,modules) $@
```

(Just off the top of my head, something's probably not right in there)

**Comment by rybesh** [comment]
> This is what we had been using Lerna to do. I have never run npm link, and it's not part of the makefile.

Right—I was referring to what I did to set up my local copy of the repo so that I could both `npm install` within each module dir (or more generally use npm commands on a module without getting errors) *and* still build the root project using Lerna.

One easy fix might be to keep everything else the same but just add make explicit targets for each necessary intermodule dependency symlink, e.g.:

```makefile
modules/periodo-app/node_modules/periodo-utils:
        cd modules/periodo-app && npm link ../periodo-utils

modules/periodo-app/node_modules/periodo-common:
        cd modules/periodo-app && npm link ../periodo-common
```

etc.

**Comment by ptgolden** [comment]
> Right—I was referring to what I did to set up my local copy of the repo so that I could both npm install within each module dir (or more generally use npm commands on a module without getting errors) and still build the root project using Lerna.

Yes, I get that. I'm just saying, by removing those dependencies, I couldn't build the project anymore and it wasn't clear why.

`npm link` isn't really the right tool for the job. Yes, it works, but now you are depending on a system-wide npm registry (`$HOME/lib/node_modules`) rather than just the `node_modules` in our project.

This is moot because I removed Lerna. 40c7a7ea0b152c237e15412f79740049de452bab

**Comment by rybesh** [comment]
👍

**Comment by ptgolden** [comment]
Everything is updated, except for `natsort`. Looking at the (very few) changes in that repo between our version and the version that doesn't work, I propose we just keep using the one we currently use since it's simple and it works.

If you feel otherwise we can keep this issue open, otherwise it can be closed
