### ISSUE TITLE
Handling spatial coverage

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#26]
Adam in #23:

> For spatial coverage, I'll take anything that can provide URIs and polygons for regional administrative divisions (e.g. "Sicily", "Toscana", "Texas") and for continental aggregations (e.g. "Europe", "North America", "Africa"). Geonames will at least resolve eastern, southern, northern Europe etc (e.g. http://www.geonames.org/7729883/northern-europe.html), and handles regions (e.g. http://www.geonames.org/2523119/sicilia.html). Does DBpedia do this too?

**Comment by sarahab** [comment]
The "Edit" for an individual periodization (within a collection, in this case Life in Biblical Israel, aka King and Stager 2001 [Harvard citation, #9 ]) is not currently functional. See screenshot: 
![20150330_periodization_edit](https://cloud.githubusercontent.com/assets/10801404/6898523/54866042-d6c0-11e4-8d3f-888cc9623f33.jpg)

So, to illustrate other issues, I see that what I entered for this periodization was its spatial_coverage_name -- though there was no place to enter spatial_coverage_label (which all the other periodizations from Life in Biblical Israel currently have). It would also be good to clarify that the current "Notes" are notes_project, there is no place to enter notes_original.

**Comment by ptgolden** [comment]
Can you tell me which browser you are using?

**Comment by ptgolden** [comment]
The latest version of the period editing form has support for spatial coverage labels and clarifies the difference between project notes and source notes.

**Comment by rybesh** [comment]
Closing this issue as it is not specific enough to guide current development.
