### ISSUE TITLE
Problems changing the primary label of existing periods

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#269]
The Priestley authority was a rabbit-hole; while fixing the spatial coverage issues, I discovered a number of things that the original creator of this authority misunderstood about the source. Some of these required a change of the primary label of a period (e.g. "Spanish Empire of Mexico" is actually just "Spanish Mexico"; the "Empire of Mexico" is the Aztec Empire).

In submitting the patch for the revisions, however, I see that the changes to the label appear at the submission stage, but then disappear from the marked changes at the review stage. I think that I've run into this before, or something similar, in issue #231, though there I thought it was because I submitted the patch more than once. 

I think there is an issue somewhere with the changing of labels for periods already in the canonical dataset. I am trying to keep the need to make these changes to a minimum, but it will definitely come up now and then. I think it's important that we resolve this one. There doesn't seem to be a problem with adding new labels -- just changing existing ones.

**Comment by atomrab** [comment]
I wonder if this isn't related to the behavior that -- on the editing of an original primary label -- changes the former primary label into an alternate label. In the cases I'm looking at, I then deleted that alternate label, because the original primary label wasn't a non-preferred but valid form, it was just incorrect. Is the point here to preserve a paper trail of previous names for a given period, even if it turns out they were not just non-preferred but wrong? Should I not delete those alternate labels when they appear? If we need to keep them for the purpose of consistency, I wonder if we couldn't include a flag to mark them as incorrect where necessary (a "danger don't use" indication of some sort).

**Comment by atomrab** [comment]
So I tested this with the most recent patch -- changed the primary label but did not delete the alternate label that appears for the old primary label. The primary label change was successfully merged, but we're still stuck with the misleading alternate label, which we don't want to keep if it's not a real version but a mistake on the part of the person who recorded it (here, a misquote of the source):

![image](https://user-images.githubusercontent.com/4740995/84433591-23d8c480-abf4-11ea-927a-517cff858831.png)

**Comment by atomrab** [comment]
But does this make it possible to get rid of the bad label altogether? The issue in these cases isn't switching which of several valid options is preferred; it's that the original label was a mistake (like our old embarrassing Pleiades "2nd millenium BC"). You can't just edit the primary label to fix a typo, because then the version with the typo just becomes an alternate label.

**Comment by rybesh** [comment]
Yes, this change fixes the bug that was causing correction of the preferred label to move the old (incorrect) label to the alternate labels:

 https://github.com/periodo/periodo-client/commit/7b319bc7df0b055376901bea9f33508c675922c9

We're just leaving the bug open until this version is deployed.

**Comment by atomrab** [comment]
This worked properly for the Priestley patch in question.

**Comment by ptgolden** [comment]
Great! I'll close this, then.
