### ISSUE TITLE
British Museum spatial coverage

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#270]
When we pulled in the very large set of definitions from the British Museum, we translated their spatial coverage directly to DBpedia (now Wikidata) entities, on the basis of the period labels themselves, which often had no additional information in the original spreadsheet we received, but were obviously connected to a particular country or region (e.g. http://n2t.net/ark:/99152/p08m57h44p7). 

As a result, we still have 822 "no value" results in our spatial coverage filter box, which is both annoying and confusing, since it suggests that we don't have coverage that we do. While we wait for an option to filter the map by bounding box, what should we do to address this? If we switch to the spatial coverage from Wikidata, we'll lose a bunch that have no corresponding entries.

I see two options here: one, to add the Wikidata values to the source spatial coverage description for the BM, which will take care of the vast majority of these (we can add a note to explain that it wasn't explicit in the definitions but obvious from context); or two, where we have no description but a Wikidata value, provide the label of the Wikidata value in place of the source description in the filter box, so that people can see that we have more than 32 values for Japan, for example. I guess we could also have an additional Wikidata spatial coverage filter, but that adds a lot of clutter. Thoughts on this?

**Comment by rybesh** [comment]
In my view, the links to Wikidata places are our editorial additions to period definitions. Typically there are an approximation of the stated spatial coverage in the source, but if there is no stated spatial coverage yet we can infer some, that should be OK too.

In those cases I think we should still leave the spatial coverage description field blank.

Currently the spatial coverage facet in the period browse UI shows unique values of the spatial coverage description field.

Maybe we should change that facet so that if the spatial coverage description field is blank, the facet value is a concatenated list of the preferred English labels of the linked places (if any).

Thoughts @ptgolden ?

**Comment by rybesh** [comment]
So to clarify I think we should do this one of Adam's two options:

> where we have no description but a Wikidata value, provide the label of the Wikidata value in place of the source description in the filter box, so that people can see that we have more than 32 values for Japan, for example. 

@atomrab note that we already have this:

> I guess we could also have an additional Wikidata spatial coverage filter, but that adds a lot of clutter. Thoughts on this?

It's under `Filter periods` > `By place`, click `Select places`:

https://client.staging.perio.do/?page=backend-home&backendID=web-https%3A%2F%2Fdata.perio.do%2F

**Comment by atomrab** [comment]
Right, I see this -- that makes sense, and deals with cases where people are specifically looking for Japan (as long as we make that clear in the documentation). But for the casual browser, I'm still bothered by the fact that you scroll through the spatial coverage list to see only 32 values labeled "Japan", and unless you do a specific spatial search, you don't know that there are another 235.

Since filter from a list and search free text are different user interactions, I'd still love to see the inferred values show up in place of "No Value" where those values are missing, on an aesthetic/user ease level. But the fact that there's a coverage search already makes this a lot less urgent.

**Comment by ptgolden** [comment]
So the choices are:

1. Add in inferred values for periods without spatial coverage descriptions

2. Break the rules a little bit, and put an inferred value in the spatial coverage description, then make an editorial note that this value was inferred, not included in the original text

Both of these are sensible enough, and also slightly inconsistent

**Comment by atomrab** [comment]
Could we provide the inferred values -- only in the filter box -- in italics, or with an asterisk, or in brackets, or with some other stylistic indicator that they're not the same as the authority claims, and explanation elsewhere? To be clear, I don't want to add them to the records themselves, just throw the "spatial coverage" value into the filter where "spatial coverage description" is missing.

**Comment by ptgolden** [comment]
Yes, I understand what you mean.

It seems strange to have both [place] and [place*] (e.g. Japan and Japan* or Japan and Japen [inferred]) as distinct facet values. Especially because they won't appear next to each other, given that facets are sorted by count, not alphabetically

**Comment by atomrab** [comment]
That's true, but it's already an issue for values like "Italy" vs "Southern Italy" vs "Italy minus Sicily". I usually used control-F in my browser to look for filter values and make sure I'm not missing anything. What bothers me most is that it distorts the perception of our coverage in the filter -- there are nearly 1000 missing values, and when you go to Japan, it looks like we've only bothered to document a few periods.

Also, better to sort facets alphabetically, since there the user will know where in the list to expect a particular value? Sorting by count is also implicitly saying something about coverage, but it's an inaccurate statement as long as we have all the undefined values.

**Comment by ptgolden** [comment]
Yeah... each method has its advantages and drawbacks. One thing we could do is allow choosing whether you want to have periods faceted on spatial coverage description OR spatial coverage entities. Because each are useful, but signify different things

**Comment by ptgolden** [comment]
How does [this](https://client.staging.perio.do/?page=backend-home&backendID=web-https%3A%2F%2Fdata.staging.perio.do%2F#Layout=%7B%22Facets%22%3A%7B%22settings%22%3A%7B%22spatialCoverage%22%3A%7B%22sortBy%22%3A%22label%22%2C%22use%22%3A%22entities%22%7D%7D%7D%7D) look to you Adam? I added the ability to sort facets by label, and calculate spatial coverage facets using entities rather than descriptions in #275

**Comment by atomrab** [comment]
That works for me. I think it's a good compromise between user-friendliness and yielding to logical inconsistency. We'll just have to be really clear in the documentation that those "undefined" values almost all have actual spatial coverage, just not descriptions from the source.
