### ISSUE TITLE
Why does the Library of Congress Subject headings authority in the new client read "Library of Congress Subject Headings whoop"?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#279]
Um, so literally:

![image](https://user-images.githubusercontent.com/4740995/86498204-6e101a00-bd4a-11ea-8a78-f7651a2dae49.png)

... hah hah...?

**Comment by rybesh** [comment]
You're looking at the data on the staging server, which we make a bunch of spurious edits to when testing things.

**Comment by rybesh** [comment]
Note that if you want to look at the real data using the client on staging, you can add a new remote data source with the URL: https://data.perio.do
