### ISSUE TITLE
Clicking "edit period collection" button in local copy switches you to the web backend

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#28]
I. periodo-client backend with synced dataset
2. click on Hodos 2006 collection
3. click "edit period collection"
4. URL changes to https://test.perio.do/#periodCollections/p0tns5v/edit/, but action is just to switch "current backend" at top of page to "web" (edit window does not come up)

**Comment by ptgolden** [comment]
This is fixed in 1c5dc81504da1beaaf0d3e748c0d930d0316ba88. It'll be deployed later today.

**Comment by atomrab** [comment]
The last time I tried in both Firefox and Chrome (4/10), this still just switched you to the web backend. I cleared my cache, but now I can't get into an editable version at all.

**Comment by atomrab** [comment]
Update: having gotten an editable local version to work on Firefox after deleting the entire cache, clicking on the edit collection button still just switches the back-end to "web".

**Comment by ptgolden** [comment]
I didn't get a chance to release the latest version on Friday. It's fixed in 0.4.0.
