### ISSUE TITLE
Map behavior is a little irregular: zoom buttons, projection, aspect ratio

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#281]
I like the way the period coverage is indicated on the map, and I understand the real-estate problems we have with this. But I'm struggling with the fact that the map is in a rectangular box in what seems to be a very elongated cylindrical equal-area projection, so I can't see the whole earth at once (just a slice of North America and Europe). My first inclination is to click on the (-) map control to zoom out, but clicking on that button actually zooms in one step (after that, it functions normally). 

Is there a more effective way to display the map, like in a square box with a web Mercator projection? I don't want to quibble, because otherwise I think it's very effective, and once you've selected a period it is pretty clear where it is -- but especially if we eventually want to use this for searching by bounding box, it would be very helpful to have a better view.

**Comment by rybesh** [comment]
We can change the projection of the map, though it will require me reading up on map projection math.

Something is wrong with the zoom buttons; I'll look into that.

Making the map a square is tricky because then it either takes up an enormous amount of screen real estate or requires a redesign of the layout. What if it were just vertically resizable?

**Comment by ptgolden** [comment]
#282 is great. I have one more thing to add. When I select a period that has a small spatial coverage (e.g. [Virginia](https://client.staging.perio.do/?page=backend-home&backendID=web-https%3A%2F%2Fdata.staging.perio.do%2F&periodID=p086kj9ksh2#Layout=%7B%22Facets%22%3A%7B%22selected%22%3A%7B%22authority%22%3A%5B%22p086kj9%22%5D%7D%7D%7D)), the map zooms in so far that it's unclear what it's zoomed to. I understand why it's doing this- it's making the bounding box fill the entire map. Might there be a way to have some heuristic maximum zoom level when showing a selected period on the map?

**Comment by rybesh** [comment]
I'm not done…

**Comment by rybesh** [comment]
OK, now I'm done. The thing that I finally figured out is that the mixmap code was adjusting the projection based on the aspect ratio of the map viewport, which was making it really difficult to determine how to set the viewport / zoom correctly when focusing on a set of features. Removing that made things make sense, and it seems to be working OK now.

**Comment by rybesh** [comment]
Examples:
* [Virginia](https://client.staging.perio.do/?page=backend-home&backendID=web-https%3A%2F%2Fdata.perio.do&periodID=p086kj9fgzn#Layout=%7B%22PlaceFilter%22%3A%7B%22filter%22%3A%7B%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1370%22%3A%7B%22id%22%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1370%22%2C%22label%22%3A%22Virginia%22%7D%7D%7D%7D)
* [Eurasia](https://client.staging.perio.do/?page=backend-home&backendID=web-https%3A%2F%2Fdata.perio.do&periodID=p0s2rwk9v36#Layout=%7B%22PlaceFilter%22%3A%7B%22filter%22%3A%7B%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ48%22%3A%7B%22id%22%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ48%22%2C%22label%22%3A%22Asia%22%7D%7D%7D%7D)
