### ISSUE TITLE
Client requests patch from wrong server

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#285]
Patch 262 was merged on production:

https://data.perio.do/patches/262.json.html

But If I use the staging client to review the history of the production server, and I attempt to view patch 262, it makes two requests to the staging server, which fail: 

https://data.staging.perio.do/patches/262/patch.jsonpatch
https://data.staging.perio.do/d/?version=171&inline-context

Error in the client:

https://client.staging.perio.do/?page=backend-patch&backendID=web-https%3A%2F%2Fdata.perio.do&patchID=http%3A%2F%2Fn2t.net%2Fark%3A%2F99152%2Fp0h%23change-262

**Comment by ptgolden** [comment]
weird, I'll check

**Comment by ptgolden** [comment]
It works when reviewing the "submitted change" (from patch requests, not history): http://localhost:5002/?page=review-patch&backendID=web-https%3A%2F%2Fdata.perio.do%2F&patchURL=patches%2F262%2F

**Comment by ptgolden** [comment]
Oops, I meant:

http://client.staging.perio.do/?page=review-patch&backendID=web-https%3A%2F%2Fdata.perio.do%2F&patchURL=patches%2F262%2F

**Comment by rybesh** [comment]
Yeah it's just the history view

**Comment by ptgolden** [comment]
It's the `permalinkAwareFetch`. It's replacing our n2t.net/:ark/99152 with `globals.periodoServerURL` rather than the canonical URL. We should have a map of n2t URLs to what they resolve to instead

**Comment by ptgolden** [comment]
`globals.periodoServerURL` is just the default server to be used as a backend when we deploy, not the canonical URL necessarilly

**Comment by ptgolden** [comment]
I'll fix

**Comment by rybesh** [comment]
> We should have a map of n2t URLs to what they resolve to instead

Why a map? Our ARK URI only ever points to one place at a time

**Comment by ptgolden** [comment]
Right, I mean that instead of having a global that we set on deploy time (`PERIODO_PERMALINK_URL`), we just hardcode known ARK URIs (i.e. ours)

**Comment by rybesh** [comment]
👍

**Comment by ptgolden** [comment]
Should be fixed by 2a953f375d04c627211750288e44f8bd49410f1f

**Comment by ptgolden** [comment]
We can take `PERIODO_PERMALINK_URL` out of the deploy script, too. It's not used anywhere now.

**Comment by rybesh** [comment]
cool, i'll do that

**Comment by rybesh** [comment]
can you take it out of index.html too?

**Comment by ptgolden** [comment]
https://github.com/periodo/periodo-client/commit/52056021af4fc973879803475f82f1f074512587
