### ISSUE TITLE
Our basemap is missing inland water

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#286]
I was trying to figure out what was confusing about the map, and I just realized that the map layer has no lakes. While this is a little weird for major rivers, the deltas and depressions make it possible to follow these, and of course minor lakes aren't a real concern. But the absence of the Great Lakes, Lake Victoria, the Dead Sea, the Aral Sea, etc. is jarring. Any chance this is as simple as adding an inland water layer to the basemap?

**Comment by rybesh** [comment]
It looks like we can switch from the [Natural Earth II with Shaded Relief and Water](https://www.naturalearthdata.com/downloads/10m-natural-earth-2/10m-natural-earth-ii-with-shaded-relief-and-water/) tiles we're currently using to the [Natural Earth II with Shaded Relief, Water, and Drainages](https://www.naturalearthdata.com/downloads/10m-natural-earth-2/10m-natural-earth-2-with-shaded-relief-water-and-drainages/):

![ne2](https://user-images.githubusercontent.com/84592/87342878-fc8a5580-c519-11ea-85c0-b4ea721af137.png)

…or if you'd prefer we can try [Cross Blended Hypso with Shaded Relief, Water, and Drainages](https://www.naturalearthdata.com/downloads/10m-cross-blend-hypso/cross-blended-hypso-with-shaded-relief-water-and-drainages/):

![other](https://user-images.githubusercontent.com/84592/87343192-7b7f8e00-c51a-11ea-9b62-66ecc113fec4.png)

**Comment by rybesh** [comment]
I decided to go with the latter. b0d5436807a3ce29f79ed84d79431e3e66dca6f3 changes the map tiles to give @atomrab his precious Great Lakes 😄 

<img width="849" alt="Screen Shot 2020-07-14 at 2 56 32 PM" src="https://user-images.githubusercontent.com/84592/87470831-5e66c000-c5eb-11ea-8264-d3abc99f0a03.png">

**Comment by atomrab** [comment]
Hey, man, one of my kids was born in Michigan, and my wife is from Chicago
(well, Evanston). I feel lost without them!

**Comment by atomrab** [comment]
The map looks awesome, by the way. Thanks for the solution!
