### ISSUE TITLE
Displayed period should default to selected period when not hovering

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#294]
Currently if there is a selected period, and then you hover a different period (changing the displayed period) and then stop hovering, the 2nd (previously hovered) period is still displayed, though nothing is hovered and there is still a selected period. Confusing!

**Comment by ptgolden** [comment]
The perils of a last minute feature addition

**Comment by ptgolden** [comment]
Fixed by b22c8c9d9385f9f442de574761dcd6d387f611c8. Wait til you see how dumb it is.
