### ISSUE TITLE
Error accepting changes for patch #281 on patch review page (Mac OS 10.12.6, Firefox 83.0)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#304]
I can log in with ORCID and I see the "accept changes?" module as usual, and I can comment, but when I click on "accept", I receive the following non-specific error message after the processing wheel spins for a couple of seconds:

![image](https://user-images.githubusercontent.com/4740995/101495859-ad144e00-392e-11eb-84b0-4624300a4f95.png)

**Comment by atomrab** [comment]
Sounds like the issue was an actual error with the patch?

**Comment by rybesh** [comment]
Yep!
