### ISSUE TITLE
Client IDB not available in either Firefox or Chrome

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#31]
I'm not sure if this is a function of being unable to log in (I cleared my cache to see if other issues would resolve; I had previously been logged in, and able to see the IDB on Firefox but not on Chrome) or a problem with the interface, but my only options are to either use the view-only web back end or to make a new back-end of my own (which doesn't work when I click Add in either Firefox or Chrome). Is this intentional?

![prob2idb](https://cloud.githubusercontent.com/assets/4740995/7121036/3cf0b3de-e1d7-11e4-9dfc-b0b4faea3b8d.JPG)

**Comment by atomrab** [comment]
I take it back -- the Add button actually does seem to work in both Firefox and Chrome, although no action is visible when you click on it. If you click on "add" and then click on the link to switch back-ends, the new local collection appears.

**Comment by ptgolden** [comment]
The page automatically refreshes now (version 0.4.0)
