### ISSUE TITLE
Client not displaying in Safari (12.1.2) on Mac (Sierra 10.12.6)

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#313]
On an instance of Safari where all history and all website data have been cleared, the link for the client renders a page as in the screen capture below:

![image](https://user-images.githubusercontent.com/4740995/101759904-cdafe580-3a9f-11eb-9ce8-83b2e8a2bba4.png)

The same result appears in a private window. Reloading the page or turning off content blockers has no effect.

**Comment by ptgolden** [comment]
Is this a new issue, or did you recently upgrade your OS?

**Comment by rybesh** [comment]
I think this is due to the old version (12.1.2) of Safari he's using; it works perfectly in recent versions of Safari (e.g. 14.0.1). Still, we should probably have some kind of message about supported browsers. I'm not sure how to test which browsers it works on…

**Comment by rybesh** [comment]
Adam, can you look at what shows in the Javascript console on Safari when you visit the site, and then copy and paste it into a comment here?

To see the console:

Safari > Preferences, click Advanced, then select “Show Develop menu in menu bar.”

Then:

Develop > Show Javascript Console.

If we can see what error gets thrown we can check for that and show a message, which is probably more reliable than browser sniffing anyway.

**Comment by atomrab** [comment]
This is the error that shows up in the console:

[Error] Unhandled Promise Rejection: TypeError: Promise.allSettled is not a function. (In 'Promise.allSettled([dispatch(Action.InitIndexedDB),dispatch(Action.CheckPersistence)])', 'Promise.allSettled' is undefined)
	(anonymous function) (periodo-client-5.0.8.min.js:78:195427)
	asyncFunctionResume
	Ji (periodo-client-5.0.8.min.js:212:83475)
	Sj (periodo-client-5.0.8.min.js:212:101212)
	Sj
	unstable_runWithPriority (periodo-client-5.0.8.min.js:286:4000)
	Jj (periodo-client-5.0.8.min.js:212:97714)
	yj (periodo-client-5.0.8.min.js:212:93926)
	Ig (periodo-client-5.0.8.min.js:212:90524)
	bk (periodo-client-5.0.8.min.js:212:111801)
	(anonymous function) (periodo-client-5.0.8.min.js:212:113050)
	Nj (periodo-client-5.0.8.min.js:212:94066)
	ik (periodo-client-5.0.8.min.js:212:113035)
	(anonymous function) (periodo-client-5.0.8.min.js:1:117156)
	(anonymous function) (periodo-client-5.0.8.min.js:1:117211)
	(anonymous function) (periodo-client-5.0.8.min.js:1:117224)
	o (periodo-client-5.0.8.min.js:1:259)
	r (periodo-client-5.0.8.min.js:1:416)
	Global Code (periodo-client-5.0.8.min.js:1:432)

**Comment by atomrab** [comment]
We can probably test what browsers it works on by just leaving it to me, since I seem to have an unerring ability to find the right combination of old OS-not-current-browser-weird-parameters to break the site ;)
