### ISSUE TITLE
experiment.worldcat.org does not serve HTTPS

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#32]
From the "no good deed goes unpunished" file-

Since we switched the site to be served over HTTPS, we can no long make CORS requests to worldcat.org because it is only served over HTTP.

**Comment by atomrab** [comment]
How should we address this in practice? Paste in a permalink and hope that later on they make it possible? Or provide full formatted entries? It's not a big deal for the moment, since most of our next round of information will come from linked-data or otherwise non-print sources, but I can see it becoming a problem when we actually build a user community.

**Comment by ptgolden** [comment]
The only thing we can do is enter the source as non-linked data and then edit it later. You should include a note about what the linked data URL should be.

**Comment by ptgolden** [comment]
> I can see it becoming a problem when we actually build a user community.
I agree. @rybesh and I have emailed worldcat a couple times about this, and they've reported they're working on it.

**Comment by ptgolden** [comment]
data.crossref.org does work over HTTPS either.

**Comment by ptgolden** [comment]
@rybesh, what do you think?

It's frustrating that we can't "do" linked open data from the browser, and I doubt anything is going to get better in the next several months.

I guess the only thing we can do is proxy requests to LD sources through the server. It's kind of disappointing to have gotten this far without doing that, but I don't see anything else to do.

**Comment by ekansa** [comment]
Do we need to set up a proxy to go between these requests?
-E

**Comment by rybesh** [comment]
The basic problem seems to be that both Worldcat and Crossref redirect HTTPS requests for linked data to HTTP URLs. So this isn't really a problem with how they implemented CORS, it's just a basic violation of the same origin policy and [the browser is refusing to make the request](http://www.w3.org/TR/cors/#user-agent-security). Does that seem right?

We should lobby these sites to fix this; maybe enlisting some of our colleagues working with linked data to underscore the urgency. But maybe in the meantime we need a server-side proxy.

**Comment by rybesh** [comment]
Sorry, meant to say that this is a problem of browsers refusing to load mixed content rather than a same-origin policy issue.

Both Worldcat and Crossref do have HTTPS, they just aren't using it for linked data. So maybe it wouldn't be so hard to get them to fix this.

**Comment by ptgolden** [comment]
Yes, it's the mixed content, not SOP (which is what CORS is meant to address). Hopefully serving content over HTTPS is an easier ask than enabling CORS.

**Comment by ptgolden** [comment]
For now, I'm proxying through https://cors-anywhere.herokuapp.com/

(there's also https://allow-any-origin.appspot.com/)

Fixed by 3dcd354008cc501ec7c8885a7efdcaf61f8eee7e
