### ISSUE TITLE
Bad gateway error again with ORCID login

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#34]
I'm getting a 502 bad gateway error with ORCID again: first I got a bad gateway when I entered my (correct) login information, and then, when I tried again, I got the ORCID notification that PeriodO wanted to share my information -- but when I clicked "accept", the 502 bad gateway message returned.

**Comment by ptgolden** [comment]
Thanks, I'll fix this.

I should clarify, though, that signing in currently does not affect how the client works. It will only be necessary in order to submit patches to the server. I'll make sure that it works when I finish the patch submission functionality this week.

**Comment by ptgolden** [comment]
This is fixed. It was an issue with permissions on the server.
