### ISSUE TITLE
RDF/Turtle view does not currently work 

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#37]
The RDF/Turtle display button currently does not work in either the local or the web backend in Chrome.

**Comment by ptgolden** [comment]
Strange- it does for me. What version of Chrome are you using? I'm looking at it with 41.0.2272.76

**Comment by atomrab** [comment]
Version 42.0.2311.90 m

**Comment by ptgolden** [comment]
Like I said, it's not broken for me, so I don't know what the issue is. I'll try testing on another computer.

**Comment by rybesh** [comment]
I'm having the same problem as Adam using Chrome 42.0.2311.90 on OSX 10.10.3. I know the Chrome update from 41 to 42 significantly tightened security so this might be related to that (mixed content?).

**Comment by ptgolden** [comment]
Fixed by 897f9467220a2b5d190af8c5005050784adfc3cb
