### ISSUE TITLE
Problems with patch generation/submission

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#38]
Let's put anything that comes up when trying to submit a patch to the server here.

**Comment by ptgolden** [comment]
Adam:
> In both Chrome and Firefox, clicking the "Submit patch" button causes a spinning processing icon to appear at the top of the page, but nothing happens on the user side after that. When one clicks on "Submitted patches", nothing appears. Should there be some event on the user-interface side to show that something has happened?

> We tested this by adding a period (Pre-Pottery Neolithic A) to an existing collection (King and Stager) in local idbs entitled "test1" in both cases (in case something shows up on the server side).

**Comment by ptgolden** [comment]
> UPDATE: when we added a NEW collection (the British Museum thesaurus) with one new period, the "Submit Patch" produced the image below. The screen now includes the new collection (period itself not specified), the new period we'd previously added to an existing collection, and two periods that are listed as "edited" from the same existing collection that we're quite sure we did not just edit. It would be helpful in this case to see either a timestamp for the edit or some sort of view of the edits that had been made (I think this would be generally helpful, actually, for people to keep track of their own edits before submission, even if the bug is fixed). 
![4e768bc8-e81d-11e4-9691-f122bd47cf62](https://cloud.githubusercontent.com/assets/376031/7259938/76c3230e-e834-11e4-8309-528555d05a65.JPG)

**Comment by ptgolden** [comment]
Adam:
> UPDATE: submission of that patch (select all for new period collections and new periods) went through when I was logged in with my ORCID; "Submitted Patches" led to a page with the following message:

> https://test.perio.do/patches/1/
> Resolved? false

**Comment by ptgolden** [comment]
> Should there be some event on the user-interface side to show that something has happened?

Yes, something should happen if it was submitted. For whatever reason, I think it was hanging. But, in that case, you should probably get some notification about why it's not working! I'll make that happen.

**Comment by ptgolden** [comment]
> We tested this by adding a period (Pre-Pottery Neolithic A) to an existing collection (King and Stager) in local idbs entitled "test1" in both cases (in case something shows up on the server side).

I think part of the issue is that the data model changed from the last time you synced locally to this time. This explains the "phantom edits" you see when submitting a patch.

**Comment by ptgolden** [comment]
> It would be helpful in this case to see either a timestamp for the edit or some sort of view of the edits that had been made (I think this would be generally helpful, actually, for people to keep track of their own edits before submission, even if the bug is fixed).

That page is the list of edits that you have made. Or, at least, it should be. Things you seen in green are information you have added, and things in red are things that you have deleted. In the case of the period you didn't edit that turned up as edited- what I'm guessing is that it's detecting a change from the old data model to the new one, which is semantically, but not visually different. This shouldn't be the case if you start from scratch with a new "backend".

**Comment by ptgolden** [comment]
> UPDATE: submission of that patch (select all for new period collections and new periods) went through when I was logged in with my ORCID; "Submitted Patches" led to a page with the following message:
> 
> https://test.perio.do/patches/1/
> Resolved? false

That means the patch submission went through. As I indicated in #35, that's about as far as I've gotten.

**Comment by ptgolden** [comment]
From the patch on the server, it looks like you:
  * Added a period collection for the british museum thesaurus, with one period definition (Abbasid Dynasty)
  * Added a period definition to the period collection based on "Life in Biblical Israel" (also Abbasid Dynasty)

Is that correct? Sorry that it's not (yet) clear what happens after submission. This was a really tricky collection of things to implement, and if that's what you meant to do then we have gotten pretty far along.

**Comment by atomrab** [comment]
Partially correct: we added a period collection for the British Museum, with a single period definition (Abbasid Dynasty); and we added a period definition to the period collection for King and Stager/Life in Biblical Israel, but that period was supposed to be Pre-Pottery Neolithic A (see the screen grab above). So it looks like the period added to the existing collection was somehow overwritten by the period added to the new collection?

Still, I think we have come a long way! Nice work here!

**Comment by ptgolden** [comment]
Huh, strange. Yes, looks like they got jumbled:

```
         "originalLabel" : {
            "eng-latn" : "Abbasid Dynasty"
         },
         "label" : "Pre-Pottery Neolithic A",
```

I'll try to see what's going on there

**Comment by ptgolden** [comment]
I'm going to write some automated tests before I try to diagnose anymore- thank your for pointing out some of the rough edges.

**Comment by sarahab** [comment]
Signed in to ORCID, the "Submit patch" screen showed an overview of my patch, "continue," then on the "Confirm" page I click "submit"  ... then instead of a _confirmation message_ it returns me to the "Submit patch" page. I think that's a bug, because when I get out of that page by "switching" (to the same thing) I see I've submitted two patches of the same thing. 3 Screenshots below:
![20150422_submit_patch](https://cloud.githubusercontent.com/assets/10801404/7288512/47b43360-e928-11e4-9eee-3e76adea6c8a.jpg)
![20150422_submit_patch2](https://cloud.githubusercontent.com/assets/10801404/7288513/4e967274-e928-11e4-9492-2ec731f64af5.jpg)
![20150422_submit_patch3](https://cloud.githubusercontent.com/assets/10801404/7288516/5420c9e2-e928-11e4-8438-7738a8d23c19.jpg)

**Comment by ptgolden** [comment]
This is most likely a confluence of the issues that you and Adam pointed out after testing out my initial implementation. I'd recommend not submitting anymore patches until I'm able to diagnose the problem.

**Comment by atomrab** [comment]
The patch submission for the test1 IDB now shows that the Pre-Pottery Neolithic A period from King and Stager has been partially overwritten by the Abbasid period that was supposed to be part of the new BM collection (which doesn't seem to have any new period attached to it):

![image](https://cloud.githubusercontent.com/assets/4740995/8684704/8fd70462-2a3f-11e5-8944-86dcbf704618.png)

**Comment by ptgolden** [comment]
can you start from scratch and see if the same thing happens

**Comment by atomrab** [comment]
So I started again from scratch and did the following, using version 1.0.13 on Chrome:

1. Created new IDB (“test3”)
2. Menu>Get data from server
3. Sync with test.perio.do
4. When given choice of items to select, selected existing collections for Twist and King/Stager
5. Continue
6. Yes
7. Clicked on PeriodO to return to test3 idb (probably need a smoother way back to the dataset from the sync page – unless back button is suggested; same is true about backing out of collections to faceted browse page – back button or PeriodO is only option)
8. Added period to King and Stage – PPNA 
9. Added collection Library of Congress Subject Headings
10. Added period to that collection – Dorian Invasions
11. Menu>submit patch
	a. Selected all
	b. Submit changes>Yes – then nothing happens
	c. No patch submission appears in the submitted patches area or the review patches area

I then tried to edit an existing period in an existing collection in a separate local idb (test2), with the following results:

1. Selected Yon 2006 collection
2. Clicked on period "Late Bronze Age", for which there was a bad end date (see #61).
3. Clicked on Edit.
4. Unchecked the automatic date parsing box.
5. Changed the latest end date from "-0084" to "-1184".
6. Saved.
7. Selected "Submit patch to server" from the menu. 
The resulting view was the following:
![submit_patch_yon_edit](https://cloud.githubusercontent.com/assets/4740995/8709993/1765a70e-2b0c-11e5-9bd8-05bd3ad821d0.JPG)
Nothing was marked in green or red to indicate changes, and the dates didn't show up at all. Only the spatial coverage and label were visible.
8. Checked all and clicked "Continue".
9. Clicked "Yes" to Submit changes.
This produced the same result as the previous -- nothing visible happened when I hit "yes", and no patches appeared as submitted or available for review.

I downloaded the JSON-LD files for both test2 and test3, if that will help.

**Comment by ptgolden** [comment]
you don't have permission to submit patches on the server. I'll tick that box, and also make a useful error if permissions are an issue.

**Comment by atomrab** [comment]
Gotcha. Let me know when I should try to resubmit, and whether you want the JSON files.

**Comment by ptgolden** [comment]
actually, that wasn't the problem. if you sign out and sign back in, you will be able to submit patches. this will not be a normal thing that will be required in the future.

you still won't be able to accept patches from the "review patches" section, because that is a permission issue. I'm going home so I won't get to it until tomorrow or Friday.

**Comment by atomrab** [comment]
Got it! I signed out and in, and this time the submission worked just fine, including the formatting for the changes and the message that the patch had been saved. I can't view the details of the submission, but this may also be a permissions issue. I submitted patches from both idbs. Thanks!
