### ISSUE TITLE
"Locator" property of period definitions not correctly translated in form

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#40]
Locator property should be nested, like:
```
"source": {
  "locator": "page 367",
  "partOf": "http://www.worldcat.org/oclc/47825690"
}
```
Currently, the form just serializes it as `"locator": "page 367"`.

**Comment by ptgolden** [comment]
this should be done in a migration for the database so that existing added periods don't break.

**Comment by atomrab** [comment]
Is this why the source locator for entries that have a page number rather than a URL doesn't appear in any of the period definitions?

**Comment by ptgolden** [comment]
locators appear as of b502ad3e18cb99dcb2c47350017a16d726a1981f

**Comment by atomrab** [comment]
Is this issue still being addressed? At least in the case of Yon, where the source locator was the same for all entries, the locator value doesn't appear in the list view or in the source-locator field in the edit view. In this case, the locator falls after the source in the JSON, not after the individual period assertions. 

"type": "PeriodCollection",
  "source": {
    "partOf": {
      "creators": [
        {
          "name": "Yon, Marguerite.",
          "id": "http://viaf.org/viaf/75011781"
        }
      ],
      "title": "The city of Ugarit at Tell Ras Shamra",
      "yearPublished": 2006,
      "id": "http://www.worldcat.org/oclc/63390787"
    },
    "locator": "page 24"
  },
  "id": "p0zmdxz",

The same thing is true of periods in the collection "Near Eastern Archaeology. A Reader", all of which are defined on the same page (83), but NOT of Woolley 1982, whose periods are defined on different pages (here the source locator shows up fine in both the list and edit views).

**Comment by ptgolden** [comment]
Please do **not** reopen issues. I created this to track the implementation of storing locators for a particular period definition, which I finished this morning.

If you want to have a further discussion, you can comment **without reopening the issue**. What you are referring to is something different that we can discuss tomorrow.

**Comment by ptgolden** [comment]
the source-based locator now shows up in the collection page. It will not show up for individual period details. I don't have time to do any more than that.

**Comment by atomrab** [comment]
Will this be true for new periods entered as we move forward (that is, if the collection only refers to one page, it will only appear in the collection detail, but if it refers to multiple pages, it will appear in the period details -- like Yon vs Woolley)? Or is this only the case for periods already in the dataset?

**Comment by ptgolden** [comment]
All of them, existing and future
