### ISSUE TITLE
bootstrap.css.map 404

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#43]
This is extremely minor, but when I load the client in Safari and turn on the developer tools I get this error in the console:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.css.map, line 0)
```
I guess this is because Safari automatically looks for CSS source maps? Any reason not to include one?

**Comment by ptgolden** [comment]
We don't minify our CSS, so it's not necessary. I just took out the source map URL for now; if we decide to serve minified css, we can put it back in.

Fixed in e972e1c2f9034eaca0c5cbfe44e3cef58c0ac56a
