### ISSUE TITLE
Browser webGL error on up-to-date Firefox on older Windows 10 machine

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#441]
This is unlikely to be a major problem for others, because it appeared on a ten-year-old Dell PC running Windows 10 and approaching the end of its support life, but this error appeared when attempting to load the client visualization interface in a current version of Firefox:

Client error
Error: (regl) webgl not supported, try upgrading your browser or graphics drivers http://get.webgl.org/
Error stack

raise@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:280:26103
onDone@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:280:40118
parseArgs@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:280:43223
wrapREGL@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:280:154755
Map@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:179:151803
[328]</module.exports@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:179:147187
initializeMap@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:78:196617
componentDidMount@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:78:202957
Ji@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:83568
Sj@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:101068
[835]</exports.unstable_runWithPriority@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:318:3998
cg@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:45420
Jj@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:97768
yj@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:93978
[780]</fg/<@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:45711
[835]</exports.unstable_runWithPriority@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:318:3998
cg@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:45420
fg@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:45658
gg@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:45591
Ig@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:90595
enqueueSetState@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:224:49383
[822]</F.prototype.setState@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:280:1325
[119]</withLoadProgress/</loadData/<@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:78:102316
[117]</combine/<@https://client.perio.do/periodo-client-5.0.11-44-gf51a871.min.js:78:81685

Component stack

in _Map
    in div
    in UI:Box
    in UI:WorldMap
    in div
    in UI:Flex
    in UI:LabeledMap
    in div
    in CoverageMap
    in div
    in UI:Box
    in LayoutBlock
    in div
    in UI:Box
    in UI:Section
    in details
    in UI:Box
    in UI:Details
    in div
    in UI:Box
    in LayoutRenderer
    in Unknown
    in Navigable
    in div
    in UI:Box
    in BackendHome
    in RenderErrorHandling
    in BreadcrumbedComponent
    in Connect(BreadcrumbedComponent)
    in ResourceLoader
    in ReduxStoreComponent
    in MenuedComponent
    in BackendKnower
    in Connect(BackendKnower)
    in Resource:backend-home
    in div
    in UI:Box
    in div
    in UI:Grid
    in ThemeProvider
    in PeriodoApplication
    in ORGShell
    in IndexedDBChecker
    in ThemeProvider
    in Provider
    in Shell

**Comment by rybesh** [comment]
I think this is probably a specific problem with this machine; all browsers have supported WebGL for a long time now.
