### ISSUE TITLE
Minor: "source is linked data/source is not linked data" confusing

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#46]
It's not clear from the user interface that here we mean "CITATION has a linked data representation in WorldCat etc", rather than "Dataset is represented as linked data". Change wording with reference to citation to avoid confusion?

**Comment by ptgolden** [comment]
thanks, I'll look into doing that.

**Comment by rybesh** [comment]
![screen shot 2017-05-12 at 10 44 56 am](https://cloud.githubusercontent.com/assets/84592/26003220/12dcf848-3700-11e7-99c4-414f625a0a5c.png)

**Comment by rybesh** [comment]
Suggest that we change this to: "The source is in WorldCat or has a DOI"  "I will enter the description of the source manually."

**Comment by atomrab** [comment]
+1

**Comment by rybesh** [comment]
This is still an issue in the new UI:
<img width="414" alt="paste-permalink" src="https://user-images.githubusercontent.com/84592/65723773-163ad900-e07d-11e9-98a9-3eb03933a095.png">

**Comment by rybesh** [comment]
fixed in master

<img width="840" alt="Screen Shot 2020-05-12 at 7 14 01 PM" src="https://user-images.githubusercontent.com/84592/81754702-d2b6a300-9484-11ea-96de-30e66cb13233.png">
