### ISSUE TITLE
Linking an author without LD citation

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#48]
Can we query VIAF for an author ID in the source field even when the user doesn't have a WorldCat etc. citation? For example, adding the CHGIS material, I put in "Merrick Lex Berman" -- would be nice to attach him to the VIAF entry. If so, we will have to specify how the name should be entered (last name, first name or first name, last name, etc.).

**Comment by ptgolden** [comment]
> If so, we will have to specify how the name should be entered (last name, first name or first name, last name, etc.).

Unfortunately, this is not consistent even in the LD sources.

I think this is something that I don't want to bake into the client, and instead leave it to preference and custom for curators. Maybe each server could have a note for potential contributors setting guidelines for acceptable data.

**Comment by atomrab** [comment]
Yeah, I can see that. With the country names, you had a limited set and you imported the whole thing, right, so we're not running a live query against a SPARQL endpoint? I was going to suggest we run a live query by last name against VIAF in this field, but that's probably way too complicated for too little payoff. I'm not that concerned about formatting -- what I really don't want to lose in this case is the connection to VIAF, so that our data, when consumed by a third party, has Lex when he's in a publication catalogued in WorldCat, but not Lex when he's giving us a spreadsheet.

**Comment by ptgolden** [comment]
> but that's probably way too complicated for too little payoff.

That's my thinking, too.

**Comment by atomrab** [comment]
So I assume we give up on VIAF for non-linked citation information, right? Or could we add a field for manual input of a VIAF identifier if the user wanted to bother looking it up?

**Comment by rybesh** [comment]
I suggest we don't implement VIAF resolution through the client until/unless there is more funding; for now if someone wants to add missing VIAF identifiers to the dataset it could be done outside the client.
