### ISSUE TITLE
Language/script selection window doesn't close on ok in Firefox

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#49]
When a language/script is entered, the entry is updated, but the window will not close when the "ok" button is clicked (in Firefox 38.0.5).

**Comment by ptgolden** [comment]
thanks, I'll look at this. I'd rather not have a modal window at all.

**Comment by ptgolden** [comment]
This is implemented as a dropdown since 6a02a1158ddb9e2bdb13917e004f62065780ad30
