### ISSUE TITLE
Make rough implementations of visualizations

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#5]
Before spending too much time on any specific visualizations, we should come up with a melange of rough demonstrations

**Comment by ptgolden** [comment]
Filtering and search by language, source (title), and spatial coverage description was implemented in #44.

**Comment by ptgolden** [comment]
Date ranges are partially implemented in the faceted browser by brushing over a time scale.

Browsing by language, source title, and spatial coverage description are all implemented.

**Comment by ptgolden** [comment]
I added the next-phase tag because there is much more potential work to be done with visualizations beyond the work we can finish in the immediate future.

**Comment by rybesh** [comment]
Closing this issue as it is not really specific enough to guide current work.
