### ISSUE TITLE
China does not come up in the spatial coverage lookup

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#51]
I tried China, People's Republic of China, Republic of China, Zhongguo -- nothing. Could this really be missing from DBpedia? If so, perhaps a good reason to allow spatial lookup against a gazetteer of the user's choice.

**Comment by rybesh** [comment]
Looks like China is missing from https://github.com/periodo/periodo-client/blob/d96ef96b79d1d5fa81573b890eec8acb91e64df4/src/data/dbpedia_countries.json. Not sure why as the [SPARQL query](https://github.com/periodo/periodo-client#sample-country-data) includes it... guess we just need to regenerate that list. Patrick, do you have a script you used to create `dbpedia_countries.json`?

**Comment by ptgolden** [comment]
Yeah, it was from that SPARQL query. Not sure why it was left out.

**Comment by ptgolden** [comment]
This is fixed in 30095374970d71a16894300fdd1e57c037918114
