### ISSUE TITLE
Cancel button in Add Period editing window does not work in Firefox

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#52]
I started to add a period to a local collection I'd made for the CHGIS periodization, but then decided I wanted to cancel it out to fix a mistake in the previous period I'd added. Clicking the cancel button did not cause any change to the state of the page. When I hit the back button on the browser, thinking I could back out, the client reverted to the database selection page -- and when I tried to access the local idb, nothing appeared but the following error message (the database seems to have disappeared,  even on reload):

Time: 6/14/2015, 12:11:47 AMVersion: 0.6.12Page: #p/adam local firefox/=========getEarliestYear@https://test.perio.do/dist/periodo-0.6.12.min.js:68:27247[152]</</maxFactory/entry<@https://test.perio.do/dist/periodo-0.6.12.min.js:23:3488[152]</</mapFactory/mappedSequence.__iterateUncached/<@https://test.perio.do/dist/periodo-0.6.12.min.js:22:25461[152]</</ToKeyedSequence.prototype.__iterate/<@https://test.perio.do/dist/periodo-0.6.12.min.js:24:440[152]</</src_Map__Map.prototype.__iterate/<@https://test.perio.do/dist/periodo-0.6.12.min.js:24:5926[152]</</HashCollisionNode.prototype.iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:11706[152]</</src_Map__Map.prototype.__iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:5871[152]</</ToKeyedSequence.prototype.__iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:384[152]</</mapFactory/mappedSequence.__iterateUncached@https://test.perio.do/dist/periodo-0.6.12.min.js:22:25416seqIterate@https://test.perio.do/dist/periodo-0.6.12.min.js:22:19705[152]</</Seq.prototype.__iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:23:26769[152]</</<.reduce@https://test.perio.do/dist/periodo-0.6.12.min.js:25:2108maxFactory@https://test.perio.do/dist/periodo-0.6.12.min.js:23:3444[152]</</<.minBy@https://test.perio.do/dist/periodo-0.6.12.min.js:25:5043minYear@https://test.perio.do/dist/periodo-0.6.12.min.js:68:28392describe@https://test.perio.do/dist/periodo-0.6.12.min.js:68:22272[152]</</mapFactory/mappedSequence.__iterateUncached/<@https://test.perio.do/dist/periodo-0.6.12.min.js:22:25461[152]</</ToIndexedSequence.prototype.__iterate/<@https://test.perio.do/dist/periodo-0.6.12.min.js:24:1224[152]</</src_Map__Map.prototype.__iterate/<@https://test.perio.do/dist/periodo-0.6.12.min.js:24:5926[152]</</ValueNode.prototype.iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:12067[152]</</HashArrayMapNode.prototype.iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:11970[152]</</HashArrayMapNode.prototype.iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:11970[152]</</src_Map__Map.prototype.__iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:5871[152]</</ToIndexedSequence.prototype.__iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:24:1184[152]</</mapFactory/mappedSequence.__iterateUncached@https://test.perio.do/dist/periodo-0.6.12.min.js:22:25416seqIterate@https://test.perio.do/dist/periodo-0.6.12.min.js:22:19705[152]</</IndexedSeq.prototype.__iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:23:27249[152]</</mapFactory/mappedSequence.__iterateUncached@https://test.perio.do/dist/periodo-0.6.12.min.js:22:25416seqIterate@https://test.perio.do/dist/periodo-0.6.12.min.js:22:19705[152]</</IndexedSeq.prototype.__iterate@https://test.perio.do/dist/periodo-0.6.12.min.js:23:27249[152]</</<.toArray@https://test.perio.do/dist/periodo-0.6.12.min.js:24:31118[152]</</<.toJS@https://test.perio.do/dist/periodo-0.6.12.min.js:24:31261[244]</module.exports<.render@https://test.perio.do/dist/periodo-0.6.12.min.js:70:11504[244]</module.exports<.initialize@https://test.perio.do/dist/periodo-0.6.12.min.js:70:11340[91]</</</Backbone.View@https://test.perio.do/dist/periodo-0.6.12.min.js:6:6681[91]</</</extend/child<@https://test.perio.do/dist/periodo-0.6.12.min.js:6:16593[193]</</ApplicationRouter<.changeView@https://test.perio.do/dist/periodo-0.6.12.min.js:65:25045[193]</</ApplicationRouter<.backendHome/<@https://test.perio.do/dist/periodo-0.6.12.min.js:65:26569run@https://test.perio.do/dist/periodo-0.6.12.min.js:4:18686[59]</notify/<@https://test.perio.do/dist/periodo-0.6.12.min.js:4:18930[19]</module.exports@https://test.perio.do/dist/periodo-0.6.12.min.js:3:21215@https://test.perio.do/dist/periodo-0.6.12.min.js:3:31460run@https://test.perio.do/dist/periodo-0.6.12.min.js:3:30799listner@https://test.perio.do/dist/periodo-0.6.12.min.js:3:30829

**Comment by ptgolden** [comment]
OK, it looks like something got stuck in a bad state in that collection. I'll make sure that it gets fixed when I release a new version next week.

Nothing has disappeared, the code just expects something in your dataset that's not there. Browse to https://test.perio.do/#p/ and everything should be fine- though you will not be able to use that backend for the time being.

**Comment by atomrab** [comment]
I can still see all the backends at that address, but can't get to the one I just made (only has one value in it anyway). I will just wait until I hear from you again, I guess, before putting more data in.

Ryan, this is the kind of trial-and-error that led me to put stuff in spreadsheets -- Sarah couldn't lose time, and I was worried about losing data or making new redundant databases when one broke like this. I know it's not best practice, and we certainly need to test the client, but not being able to see data you've generated in an interface is alarming for the less technically savvy.

**Comment by rybesh** [comment]
> not being able to see data you've generated in an interface is alarming for the less technically savvy

Yep, which is why we're making sure that the client has been well-tested internally before we ask the general public to use it. Remember, you're on the development team, you're not a customer... :grin:

**Comment by atomrab** [comment]
Yeah, I know. I was just trying to explain why I keep falling back on spreadsheets!

**Comment by ptgolden** [comment]
I updated the client so that it won't choke when given a period without all the data it expects. You'll see one period in the China Historical GIS list that has no label, start, or stop dates. It inadvertently got saved for whatever reason. You'll probably want to delete it.

**Comment by atomrab** [comment]
I'll be happy to delete it. It's probably the one I was trying to start
when the idb broke. Is it in the data on the server now?

**Comment by ptgolden** [comment]
no
