### ISSUE TITLE
Allow sorting in faceted browser

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#54]
By label, start date, end date

**Comment by atomrab** [comment]
And maybe by spatial coverage, if not difficult.

**Comment by ptgolden** [comment]
Yep, good idea.

**Comment by ptgolden** [comment]
This was a duplicate of #22.

**Comment by ptgolden** [comment]
Moved discussion of filtering by spatial coverage to #58. Sorting is implemented, so I'm closing this issue.
