### ISSUE TITLE
Permalink

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#55]
I suspect this doesn't matter right now, but the current period-definition-specific permalink resolves to the collection as a whole, and then for some reason incapacitates the browser back button in Chrome (it just sends you back to the same page again). Eventually we probably want to support resolution down to the period record, since human users may want to follow the link from a database.

**Comment by ptgolden** [comment]
Thanks, Ryan and I were talking about it earlier. it would be nice to have.
