### ISSUE TITLE
Filtering by spatial coverage

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#58]
@atomrab in #54 suggested that filtering could be done by spatial coverage entries (not just spatial coverage descriptions, as is currently implemented).

This may be useful but confusing/misleading because of the relationship between spatial coverage description (which is in the source) and spatial coverage (which is an estimation of that description using linked data entities).

Filtering by spatial coverage will ideally be done in a map interface- this was the primary purpose of linking descriptions with LD entities in the first place. This will be quite involved and not possible to implement this summer.

I think we should hold off on filtering by constituent parts of spatial coverage descriptions ("spatial coverages"), and stick with filtering only by descriptions. The latter will become much more useful once periodo/periodo-data#24 is resolved.

**Comment by rybesh** [comment]
This will be possible once Bits Coop has finished their spatial feature query & selection component… one will be able to click and drag on a map display to draw a bounding box and select preferred labels for features "matching" the bounding box, which we can then use to filter for definitions with spatial coverage values matching those features.

**Comment by ptgolden** [comment]
Can we mark this closed @rybesh? There's no bounding box filtering, but it's on our radar. We can create a separate issue.

**Comment by ptgolden** [comment]
(Oops, didn't mean to close)

**Comment by rybesh** [comment]
Yes, we can close.
