### ISSUE TITLE
Expose more complete collection references in client

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#59]
I think users are likely to want complete bibliographic references for the sources we're attributing collections to. Right now, these don't appear at all in the web interface, and they only appear in a local idb when you select the edit button. Either providing a full reference in the GUI by default, or allowing expansion (as we now do with periods, which is working really well), is a better option than the very abbreviated author-title-date that we offer now.

**Comment by ptgolden** [comment]
fixed
