### ISSUE TITLE
Date parsing issue (dates of type "1190/85 BC")

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#61]
One of the values for periods at Ugarit, I just noticed, didn't work with the parser (see http://n2t.net/ark:/99152/p0zmdxzj35q). The end date was 1190/85 BC, which would work now if broken into a four-part date -- but as it was entered, it was parsed as 85 BC. I can fix this manually, but if it's not too difficult to add support for dates of this format (1190/85, or 451/50, or 375/350 etc.), they are actually pretty common in the archaeological literature. It's another way of saying "somewhere within this five-year range".

**Comment by ptgolden** [comment]
slashes are treated as a range, as in {start/end}. 1190/85 BC will be treated as somewhere in the range 1190 BC to 85 BC. if you need to do something else, you can uncheck the autoparse box and enter the values you want. I'm marking this as closed because it would be complicated and unnecessary to add to the parser.

**Comment by atomrab** [comment]
The problem is that invariably when people use that formulation, they really mean 1190/1185. The usual practice is to include only the digits that change (so 421/0 is 421-420, and 350/25 is 350-325). The slash is only used when the dates involved are in the same century, at least in the periods I deal with. But I don't know how hard it is to account for this in a parser. I'll have to go back through the original dataset and find all these to change them manually.

**Comment by ptgolden** [comment]
You're right, some people mean that when they type a slash, but some people don't. The EDTF standard you linked to the other day, for example, treats slashes as an absolute range, not as relative to the same century. If anything, I will take out parsing slashes altogether.

**Comment by atomrab** [comment]
Right. I think it makes more sense to drop the slash parsing, then, and
just have people do it themselves. For the existing values, are these in
two parts? That is, does the example I passed on have earliest end -1189,
latest end -84? Or did it just keep the latest end?
