### ISSUE TITLE
Error attempting to download IDB from Chrome

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#64]
Trying to download the IDB we originally submitted as a patch (with a few corrections and one new collection with one new period), I received the following error message:

7/14/2015, 3:25:40 PM
TypeError: Converting circular structure to JSON

Chrome Version 43.0.2357.132 m, PeriodO version 1.0.12

**Comment by ptgolden** [comment]
> Trying to download the IDB we originally submitted as a patch (with a few corrections and one new collection with one new period)

I don't understand what this means.

when you get an error in the future, click on it and copy + paste the full details that pop up. it will tell me a lot more.

**Comment by atomrab** [comment]
Sorry, didn't realized I needed to click on the error message itself to get the whole issue. Here it is:

Time: 7/15/2015, 12:15:41 PM
Version: 1.0.13
Page: #p/
=========
TypeError: Converting circular structure to JSON
    at stringify (https://test.perio.do/dist/periodo-1.0.13.min.js:54:5882)
    at stringify (https://test.perio.do/dist/periodo-1.0.13.min.js:54:6056)
    at stringify (https://test.perio.do/dist/periodo-1.0.13.min.js:54:6056)
    at stringify (https://test.perio.do/dist/periodo-1.0.13.min.js:54:6056)
    at stringify (https://test.perio.do/dist/periodo-1.0.13.min.js:54:6056)
    at stringify (https://test.perio.do/dist/periodo-1.0.13.min.js:54:6056)
    at module.exports (https://test.perio.do/dist/periodo-1.0.13.min.js:54:6227)
    at https://test.perio.do/dist/periodo-1.0.13.min.js:74:16320
    at handle (https://test.perio.do/dist/periodo-1.0.13.min.js:17:2181)
    at Promise.finale (https://test.perio.do/dist/periodo-1.0.13.min.js:17:4063)

**Comment by atomrab** [comment]
>Trying to download the IDB we originally submitted as a patch (with a few corrections and one new >collection with one new period)
>I don't understand what this means.

Also, to explain: Sarah and I made a local IDB by importing a selection of collections from the server. To this, we added one new period collection containing one new period; we added one new period in an existing collection; and we edited two existing periods in the existing collection. Then we submitted a patch based on this IDB (see #38). Something went wrong at that time. This is what I'm trying to resubmit now. When it wouldn't go through, you asked me to download it and send it as a file, so you could take a look -- and this led to the download issue here.

**Comment by ptgolden** [comment]
Thanks. Echoing my comments in #38, it looks even more now like an old version of the client did not work correctly and saved your data in a bad state. If this happens on newly created local stores, let me know.

**Comment by atomrab** [comment]
Gotcha. So I assume I should just delete this store altogether.
