### ISSUE TITLE
Making editorial process clearer

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#65]
Two editorial issues probably need to be highlighted in some way for users.

1) There is no edit button in periods viewed through the period browse list; this may be deliberate, but if that's the case, we'll need to explain somewhere that the user needs to click through to the collection and then select that period again to carry out an edit.

2) You can't edit any of the citation information attached to a source that has a worldcat entry. This is probably supposed to be that way, but it might be confusing to a user, who goes in to fix a title and is faced with canceling or replacing the entry altogether by changing the linked-data source. I was looking at this with the Pedley textbook collection, which is titled "Greek Art and Archaeology John Griffiths Pedley". I assume that's because the worldcat entry has badly formatted linked data (the title on the page http://www.worldcat.org/oclc/201147248 is correct, without the repetition of the author's name), in which case, since that info is automatically populated, we probably can't change it. Is my only option to go in and find a better-formatted worldcat entry? How should we explain this to users who will see the title and say "hey, I should fix that"?

**Comment by ptgolden** [comment]
> 1) There is no edit button in periods viewed through the period browse list; this may be deliberate, but if that's the case, we'll need to explain somewhere that the user needs to click through to the collection and then select that period again to carry out an edit.

if you write documentation about this process, I'd be happy to include it somewhere.

> 2) You can't edit any of the citation information attached to a source that has a worldcat entry. This is probably supposed to be that way

yes, it's supposed to be that way.

> Is my only option to go in and find a better-formatted worldcat entry?

yes. or if the linked data is bad and doesn't actually refer to the thing you're trying to refer to, add it as a non-linked data source with an editorial note.

> How should we explain this to users who will see the title and say "hey, I should fix that"?

we should explain that we are not a bibliographic management application. if worldcat has bad linked data, someone should email them to fix it. that should not be our business.

**Comment by atomrab** [comment]
>if you write documentation about this process, I'd be happy to include it somewhere.

I'll start putting this together once we've finalized the workflow. We'll need an FAQ page for contributors anyway.

> we should explain that we are not a bibliographic management application. if worldcat has bad linked data, someone should email them to fix it. that should not be our business.

I agree, though my experience is that non-expert users will judge us for typos or errors in authors and titles, not WorldCat.
