### ISSUE TITLE
Provide contributor credit 

### ISSUE THREAD

**Issue by strongbad03** [periodo/periodo-client#67]
In the current client version (1.0.12), new period data entered into the web client didn't seem to incorporate contributor credit in the resulting linked data. Would like to see that sort of acknowledgement in a communal resource. 

Pleiades provides a good model that distinguishes between Creator and Contributor, such as [here](http://pleiades.stoa.org/places/60568):  "Creators: M.U. Erdosy. Contributors: R. Talbert, Sean Gillies, Tom Elliott, Jeffrey Becker"

**Comment by ptgolden** [comment]
Can you clarify where this is happening? I'm seeing both `dcterms:creator` and `dcterms:contributor` values in linked data produced from our sources.

This is a source without an external linked data representation, entered manually into the client:
```
<http://localhost:5000/.well-known/genid/0537b9b3a176c3fba5752105b8312385>
    a skos:ConceptScheme;
    dcterms:source [
      dcterms:contributor [
        foaf:name "person b"
      ];
      dcterms:creator [
        foaf:name "person a"
      ];
      dcterms:title "a title"
    ].
```

And linked data fetched from http://www.worldcat.org/oclc/32590556:
```
<http://viaf.org/viaf/5038048>
    foaf:name "Brendel, Otto, 1901-1973.".

<http://viaf.org/viaf/73889533>
    foaf:name "Serra Ridgway, Francesca R.".

<http://www.worldcat.org/oclc/32590556>
    dcterms:contributor <http://viaf.org/viaf/73889533>;
    dcterms:creator <http://viaf.org/viaf/5038048>;
    dcterms:issued <"1995"^^http://www.w3.org/2001/XMLSchema#gYear>;
    dcterms:title "Etruscan art".
```

**Comment by rybesh** [comment]
@ptgolden I think he is talking about credits for contributors to PeriodO, not the source creators.

@strongbad03 We have credits for contributors in the VoID description of the dataset: http://n2t.net/ark:/99152/p0/.well-known/void

Currently it just lists the PeriodO staff, but once we accept a patch the ORCIDs of patch submitters will appear there too. However, we should also probably show or link to them in the footer of the client.

**Comment by ptgolden** [comment]
Ah, right. We'll have to keep this in mind when rendering provenance information.

**Comment by rybesh** [comment]
We do also include the ORCIDs of submitters and accepters in the provenance / change history data, but again since we don't have any accepted patches yet they don't show up there.

We should probably expand `void-stub.ttl` to list all of our partners who contributed initial data... @atomrab would you be able to compile a list of people and/or organizations who gave us period definitions?

**Comment by atomrab** [comment]
Yup. At least for the non-GeoDia ones. The GeoDia definitions were
collected by a series of grad students, and although I can go back and
figure this out, it would be pretty time-consuming. We might simply credit
Sarah, who edited them.

**Comment by rybesh** [comment]
Sarah's already in there. I wouldn't worry about reconstructing the GeoDia contributions, just the partners.

**Comment by rybesh** [comment]
We now assign credit in the linked data, but it would still be nice to be able to load and display in the client contributor info for definitions and collections.

**Comment by rybesh** [comment]
http://perio.do/contributors/
