### ISSUE TITLE
Broken in Safari due to poor indexedDB implementation

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#70]
See https://github.com/dfahlander/Dexie.js/issues/77

**Comment by rybesh** [comment]
So do we want to use that indexedDBShim?

**Comment by rybesh** [comment]
And/or could we just make read-only web backend work with Safari?

**Comment by ptgolden** [comment]
yes, I'll do it. I wanted to remind myself. it's not super easy to test for the broken implementation, either. thanks safari.

**Comment by ptgolden** [comment]
is it urgent?

**Comment by ptgolden** [comment]
Fixed by 0438bfc25a0d7ea7bd471dfeda5bb3b051e6b5eb

**Comment by ptgolden** [comment]
Fixed as in, it works read-only in Safari now. I don't know how to programmatically detect the brokenness of Safari, so I'm holding off on using indexedDBShim. I made a new issue (#71) regarding showing a warning message about IDB support.

**Comment by rybesh** [comment]
Until Apple fixes Safari, I added this to our nginx.conf:
```
    set $browser "";
    if ($http_user_agent ~* "safari") {
	set $browser "safari";	
    }
    if ($http_user_agent !~* "chrome") {
	set $browser "${browser}+not_chrome";
    }
    if ($browser = "safari+not_chrome") {
	return 302 http://perio.do/safari-is-broken/;
    }   	
```

**Comment by ptgolden** [comment]
that's pretty harsh! we should definitely get it working read-only (which I thought it was?). We can discuss more when you get back.

**Comment by rybesh** [comment]
Yeah, harsh, but I saw so many people at the conference getting the error I reported in #73 that I figured it was warranted. I don't think it's a problem, would be nice to get it working read-only but in the meantime this at least lets people know what's going on...

**Comment by rybesh** [comment]
To clarify, the error in #73 is what Safari users see when first loading the client; there's no way to choose the read-only web backend.
