### ISSUE TITLE
Show useful "read-only" message/warning when IndexedDB is not supported

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-client#71]

**Comment by rybesh** [comment]
IndexedDB is supported in all the browsers we target now.

**Comment by ptgolden** [comment]
The only time I see this is if I open PeriodO in Firefox private mode. Chromium gives a temporary database; Firefox just disables IDB completely

**Comment by rybesh** [comment]
Ah, OK, I didn't realize FF did that. Re-opening.

**Comment by ptgolden** [comment]
Should be fixed by 4d602b9e8bc98ac34c7cf56d54698696c598fde6, although this still doesn't offer a "read-only" experience, just a message to change browsers
