### ISSUE TITLE
TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#73]
I'm getting a new error on Safari now on the select backends page.
<img width="373" alt="screen shot 2015-07-19 at 11 01 09 am" src="https://cloud.githubusercontent.com/assets/84592/8765478/7c7e1ad0-2e05-11e5-9609-9528b6c2ce3c.png">

```
Time: July 19, 2015 at 10:58:07 AM GMT+1
Version: 1.2.3
Page: #/p/
=========
https://test.perio.do/dist/periodo-1.2.3.min.js:15:39239
doResolve@https://test.perio.do/dist/periodo-1.2.3.min.js:17:5473
Promise@https://test.perio.do/dist/periodo-1.2.3.min.js:17:2683
open@https://test.perio.do/dist/periodo-1.2.3.min.js:15:38533
initDB@https://test.perio.do/dist/periodo-1.2.3.min.js:80:25933
getDB@https://test.perio.do/dist/periodo-1.2.3.min.js:80:25989
listFiles@https://test.perio.do/dist/periodo-1.2.3.min.js:80:26035
https://test.perio.do/dist/periodo-1.2.3.min.js:74:18441
handle@https://test.perio.do/dist/periodo-1.2.3.min.js:17:3246
finale@https://test.perio.do/dist/periodo-1.2.3.min.js:17:5132
resolve@https://test.perio.do/dist/periodo-1.2.3.min.js:17:4678
https://test.perio.do/dist/periodo-1.2.3.min.js:17:2751
https://test.perio.do/dist/periodo-1.2.3.min.js:17:5516
handle@https://test.perio.do/dist/periodo-1.2.3.min.js:17:3357
finale@https://test.perio.do/dist/periodo-1.2.3.min.js:17:5132
resolve@https://test.perio.do/dist/periodo-1.2.3.min.js:17:4678
https://test.perio.do/dist/periodo-1.2.3.min.js:17:2751
https://test.perio.do/dist/periodo-1.2.3.min.js:17:5516
handle@https://test.perio.do/dist/periodo-1.2.3.min.js:17:3099
finale@https://test.perio.do/dist/periodo-1.2.3.min.js:17:5132
resolve@https://test.perio.do/dist/periodo-1.2.3.min.js:17:4678
exports@https://test.perio.do/dist/periodo-1.2.3.min.js:1:12209
https://test.perio.do/dist/periodo-1.2.3.min.js:1:45872
run@https://test.perio.do/dist/periodo-1.2.3.min.js:1:22653
listner@https://test.perio.do/dist/periodo-1.2.3.min.js:1:45243
```

**Comment by ptgolden** [comment]
I'm not going to be able to debug this until you get back. Can you hold off on filing more Safari issues until you do? I'm sure there are a lot, and I'll go through them in a sweep of the site when I can have a browser open next to me.

Displaying "1" is not related to that issue, it's related to what I pointed out in 3b7f0835d547abeec94cc6ae19478fdd63e54537

**Comment by ptgolden** [comment]
Further, I think this might just be another case of the Safari IDB bugs, not anything with PeriodO. As I said in #70, there's no easy, synchronous way to test for Safari's broken implementation, so we need to let it fail every time and just ignore those failures. It looks like all has gone according to plan, since the application recovered from that error and rendered itself.

It's puzzling/annoying why they didn't just include IDB with a -webkit prefix if it was so incomplete.
