### ISSUE TITLE
Add page previous/next and page number buttons to BOTTOM of period and collection view pages

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#75]
These buttons are already at the top, but since most pages require the user to scroll down below the fold, especially if you've expanded some definitions, you currently have to scroll back up again to navigate. It would be very useful to have these navigation tools at the bottom of those pages as well.

**Comment by rybesh** [comment]
Yeah, that is a good idea.

**Comment by ptgolden** [comment]
Also missing is "Show 10/20/50/100/all" option

**Comment by atomrab** [comment]
+1 on the options for how many records to show.
