### ISSUE TITLE
Filter state should be persisted in the URL

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#76]
Individual period definitions expand within the same page when you click them, but when you click on a collection, you're taken to a page with no navigation that leads back to the browse page. You can obviously hit the back button or click on "PeriodO", but I think I've been conditioned to fear the back button, and using PeriodO to get back is not intuitive. I would be happier using a "back to browse" button that I knew would send me back to the previous page in an appropriate state (even better if you go back to the browse view you'd just been using -- so back from a collection to the set of collections, rather than back from collection to period browse; just saves a click).

**Comment by ptgolden** [comment]
We could have a breadcrumb situation, which is always helpful for navigation.

> but I think I've been conditioned to fear the back button

Why! I think back/forward should be fundamental parts of browsing the web.

One thing that *is* counterintuitive, which was brought up in the last advisory board meeting, is that filter criteria should be persisted in the URL. This would make the filtering interface work better with back & forward, and also allow bookmarkable filter results.

**Comment by rybesh** [comment]
Agreed that a breadcrumb might help, and that filter state should be persisted in the URL. 

We shouldn't replicate the browser's back button with our own. You can use the browser's back button with confidence when using PeriodO.

**Comment by atomrab** [comment]
Yeah, I know -- I'm not talking about rational fears, or justifiable ones. I'm giving you [the Swedish microobservation of my habitus](https://en.wikipedia.org/wiki/Kitchen_Stories), and I've noticed that I balk before hitting the browser back button. Not just here, but everywhere.

In any case, I'd be happy with a breadcrumb and/or the ability to get back to the period list without an extra click. Right now, Main page>collection tab>specific collection>back button>main page, not collection tab. Big +1 on the persistent filter state, especially if that solves the problem.

**Comment by ptgolden** [comment]
Breadcrumb added in 2.3.0

**Comment by rybesh** [comment]
Changed issue name to reflect narrowed focus.

**Comment by ptgolden** [comment]
This has been fixed with the client rewrite. Client state, including choices of filters, is persisted in the URL.
