### ISSUE TITLE
When dataset is rebuilt, don't forget to copy spatial coverage over to spatial coverage description for some collections

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#77]
I was just playing with the Fasti data and was reminded of the lack of "spatial coverage description", which makes it impossible to filter by spatial coverage (same is true of ARENA and some others). This is the case because those collections came to us already ordered by modern nation states, so we didn't include a separate description. We talked about copying this over so that those records would be complete.

**Comment by atomrab** [comment]
I can't remember, though, if I was supposed to specify which collections. It is my impression that any collection that has a spatial coverage description but not a spatial coverage label should be assumed to have stated a spatial coverage explicitly, and that the label should be copied from the coverage (eg. http://n2t.net/ark:/99152/p0wf3wd, where the coverage is Sardinia because the book is about Sardinia). But if it's preferable to do this only for collections we inherited where spatial coverage was already provided by the authority in modern terms (eg Fasti and ARENA), and make notes by hand with the rest, let me know.

**Comment by rybesh** [comment]
I think this no longer applies since we allow definitions not to have spatial coverage descriptions in cases where we are inferring spatial coverage (i.e. it wasn't explicitly stated in the source).
