### ISSUE TITLE
Why don't we have a filter by spatial coverage (not description)?

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#78]
Is there a reason we don't have this as well as the label? Just questions of space? It would actually be quite useful -- you might well want to get all the periods that had spatial coverage "Iraq" in one place, whether the original labels were "Mesopotamia", "Babylonia", "Middle East", or "Iraq". Or are we saving this for the next round and doing it with an interactive map?

**Comment by ptgolden** [comment]
duplicate of #58

**Comment by atomrab** [comment]
Sorry, forgot we'd already hashed this out!
