### ISSUE TITLE
View definitions in patches for new collections

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#85]
Once we have a larger body of contributors and have less control over who is submitting patches, it will be important for the patch review UI to show not only the new collections submitting, but also some or all of the definitions in them. Otherwise it's impossible to tell whether a) the definitions are formatted correctly (could be universally messed up in terms of time, space, etc) and b) the definitions bear some relation to reality (could be crazy periods made up by History Channel ancient aliens enthusiast -- actually could be interesting, but we are insisting on the idea of scholarly authority and evidence).

**Comment by ptgolden** [comment]
Implemented in 2b23fa0f758d17faf439b16ae89f69a1647fe3a0 and fc65fe2532843a66a9215d8ab428fe5a0b3ec108
