### ISSUE TITLE
Source Locator information disappears

### ISSUE THREAD

**Issue by sarahab** [periodo/periodo-client#86]
Working in a local IDB, I enter a web address into the field: Locator : Position within the source (e.g. page 75), and then the information disappears after clicking Save. I tried entering weblinks, page 75, and nothing sticks. This field is important, please advise.  (The URL field doesn't have this problem, but Source Locator is essential)

**Comment by rybesh** [comment]
Can you post some screenshots of what it looks like before and after you click Save? I wasn't able to reproduce this.

**Comment by sarahab** [comment]
Sure: Here's a screenshot of the information entered into Locator field:
![20150828_locator1](https://cloud.githubusercontent.com/assets/10801404/9556292/581189a8-4d99-11e5-9db7-faf7a1a3bc80.jpg)

then I click Save. Then the period just entered displays like this, without Locator information:
![20150828_locator2](https://cloud.githubusercontent.com/assets/10801404/9556296/60c1962e-4d99-11e5-90e3-7286ac9fb50c.jpg)

**Comment by rybesh** [comment]
OK, I can reproduce this now; it does seem to be a bug. Until we fix it, can you put the period definition locator URL in the editorial notes?

**Comment by ptgolden** [comment]
This does not seem to be an issue anymore
