### ISSUE TITLE
Display Source/Date of periodization in period collection page, not title

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#9]
Currently the client lists the periodizations by title, but this is both awkward (some of the titles for the web-based versions are not very informative) and not the way specialists are likely to find information (non-specialists will just want a free-text search). It would be one thing if titles provided information about spatial and cultural coverage, but they don't always (e.g. "Periods used on the database"). 

Academics are used to looking for the authority name and the date (eg Harvard citations), and I think it makes sense to list the periodizations by that header, rather than title. So instead of "Aegean Bronze Age", we might consider "Shelmerdine 2008". There's already a listed date range; if we're worried that it will then be unclear what places are described by this periodization,could we add the spatial coverage for the work as a whole?

**Comment by sarahab** [comment]
What's also missing in both the list of collections (pre- and post-sync is the same) and in the abbreviated collection view that appears when looking at its periodizations (see two screenshots below), is source_zotero_id, which we have for most of the book sources, and source_linked_data_uri.
![20150330_collections](https://cloud.githubusercontent.com/assets/10801404/6899246/c203fa68-d6c4-11e4-8ca3-e2f5c7cbe89b.jpg) and 
![20150330_collection_periodization](https://cloud.githubusercontent.com/assets/10801404/6899250/c962dffe-d6c4-11e4-9525-d3db6ca0580d.jpg)

**Comment by rybesh** [comment]
We don't keep `source_zotero_id`, that was only temporary while we were
working off of the spreadsheet. Henceforth bibliographic data will either
be drawn from WorldCat or CrossRef (when we have a `
source_linked_data_uri`) or manually entered into the client.

**Comment by ptgolden** [comment]
This has been done for a while. We might want to revisit how to format names, but we consume LD from a few different places with all different ideas of expressiveness.
