### ISSUE TITLE
Collection contributors being saved with empty strings

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#90]
In Chrome, at least, the Editorial Note header in the collection view is large, indented, and not separated from the last citation field by a space, so that it appears to encroach on the "Contributors" data field (especially when the latter is blank). It should be left-justified, separated by a line break or paragraph space from the citation fields, and probably reduced in size (though I think it's fine if it stays a little larger than the other field names).

**Comment by atomrab** [comment]
Update: I notice that this isn't a problem with local databases, since the edit collection/add period buttons separate the editorial note from the citation information. It's only a problem when viewing the canonical dataset, where those buttons do not appear.

**Comment by ptgolden** [comment]
Cosmetically fixed by 7bb3d6fa7fa6ee54e1994c1a8718ec65c94b0604

The problem was that there are contributors being saved with empty strings. Still gotta address that.

**Comment by rybesh** [comment]
Updated description to reflect new focus.

**Comment by ptgolden** [comment]
Fixed in bb457b42408b40513d31f77ec28b88cd1e03b024
