### ISSUE TITLE
Interface will not accept a value of 0 or 0000 for a start or end date

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#92]
In connection with #89, the interface does not allow the (manual?) entry of 0 or 0000 for a start or end date -- but I've already run into a BP (2000) value of 2000, which should be parsed in ISO as 0. We should allow the manual entry of zero years in the ISO field, though it might make sense to require a specific format to make sure it's not a mistake.

We supported this in the parsing and ingest of our initial dataset (e.g. http://n2t.net/ark:/99152/p06v8w4s9pz), so I assume this is an issue with data entry, not with the data model. The parser will represent 0000 for "1950 BP", and 0 or 0000 can be entered manually, but it is not possible to save the resulting entry:

![image](https://cloud.githubusercontent.com/assets/4740995/9699134/67f29e58-539c-11e5-8e9e-e2f77505f510.png)

**Comment by rybesh** [comment]
This is a bug due to zero evaluating as false:
https://github.com/periodo/periodo-client/blob/5a6b3a91ed19aaff01b24d0efba923afcdad47e4/src/helpers/period.js#L50

**Comment by ptgolden** [comment]
Fixed by ebc7e4cbab9e88b4e8775295cf064f4a8446be53
