### ISSUE TITLE
Can't delete a duplicate period value

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#93]
When I submitted the patch for the ARIADNE collection -- perhaps because of the problem with the earlier submission of a collection with no definitions -- the collection doubled the entry for "Paleolitikum". In the earlier entry, I put in "BP(2000)" with no space, but I then realized that I wanted the space, so the duplicate entry and all subsequent entries have "BP (2000)". I therefore tried to delete the extra entry for "Paleolitikum" by deleting my initial ARIADNE local idb, creating a new local idb, syncing the ARIADNE collection from the Canonical dataset with this new local idb, and then deleting the extra "Paleolitikum". 

When I tried to submit this idb as a patch, the interface tells me that "no changes are detected", even though I deleted the extra definition in my local idb. The two definitions have distinct URIs: http://n2t.net/ark:/99152/p0qhb66ptzb (old) vs http://n2t.net/ark:/99152/p0qhb66v7bp (correct). 

If I can't delete the former with a patch -- perhaps because there's some corrupted JSON from the original bad submission -- can someone delete it manually, preferably by 9/10?

**Comment by atomrab** [comment]
UPDATE: I thought that I might be able to get around this by downloading the local idb, creating a new blank idb, and then syncing it with this file, which definitely only has 45 definitions (and only one for Paleolitikum). But that also didn't work -- trying to submit a patch from this collection still produces the message "no changes detected".

**Comment by ptgolden** [comment]
Deletions are not detected yet in changes. I don't have time to work on PeriodO for a bit, but I'll address this when I do.

**Comment by rybesh** [comment]
I don't think we should support (in the client) submitting patches that make deletions. This should be a for-emergencies-only, talk-to-the-API operation.

**Comment by rybesh** [comment]
But see #122
