### ISSUE TITLE
Trouble submitting a patch, 20+ definitions

### ISSUE THREAD

**Issue by sarahab** [periodo/periodo-client#95]
I tried several times yesterday to submit a patch with two new period collections with 46 new definitions. I got all the way to the Submit changes? page, clicked Yes, then the wheel starts spinning at the top of the page. I actually let it spin overnight, tried again today, and it still does not go through--see screenshot. 
![20150915_periodo_submitpatch2](https://cloud.githubusercontent.com/assets/10801404/9909712/fcb0309e-5c5e-11e5-82d4-d827e96d1540.jpg)

So I tried selecting only one of the new collections (22 definitions) to submit half the patch at a time, and then I get a new error message:

Time: 9/16/2015, 10:23:27 AMVersion: 2.3.6Page: #/p/INRAPfound/patches/submit/=========<html><head><title>502 Bad Gateway</title></head><body bgcolor="white"><center><h1>502 Bad Gateway</h1></center><hr><center>nginx/1.8.0</center></body></html>

After the error message appears, I click Yes again, and the screen freezes. Five minutes later, I click Yes, and the wheel spins. Frustrating. (I edited data from a local IDB; if I leave this page I can at least download it with all the edits, to submit later somewhere else). Is it possible to replace the spinning wheel with a progress bar, to see if it is actually working on the patch? Is there some size limitation on patches? Another way to submit this?

**Comment by sarahab** [comment]
OK, I came back to it (restarted, signed out/in, maybe a neighbor freed up all the bandwidth or something) and now they got successfully submitted. Closing this, thank you!

**Comment by rybesh** [comment]
Glad it finally worked. In general, it should never take a long time for a patch to be processed upon submission, so if the wheel is just spinning like that, it is probably a network issue. Still good to let us know about it though, so thanks!

**Comment by sarahab** [comment]
Is there an upper limit on # of definitions submittable per patch? 25, 50, 100?

**Comment by ptgolden** [comment]
No, there's not.

My unsatisfying answer to this problem was that the server was just having a hiccup. You should have seen some sort of error message, though.
